dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Data are based on a sample and are subject to sampling variability.
        The degree of uncertainty for an estimate arising from sampling variability
        is represented through the use of a margin of error (MOE). The value shown
        here is the 90% MOE. The MOE can be interpreted roughly as providing a 90%
        probability that the interval defined by the estimate minus the MOE and the
        estimate plus the MOE (the lower and upper confidence bounds) contains the
        true value. In addition to sampling variability, the ACS estimates are subject
        to nonsampling error (Accuracy of the Data: https://www2.census.gov/programs-surveys/acs/tech_docs/accuracy/ACS_Accuracy_of_Data_2020.pdf).
        The effect of nonsampling error is not represented in these tables.'
      contact_city: Seattle
      contact_email: cnaito@psrc.org
      contact_name: Carol Naito
      contact_phone: 206-464-7535
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'The American Community Survey (ACS) is a survey conducted by
        the U.S. Census Bureau. It uses a series of monthly samples to produce annually
        updated estimates for the same small areas (census tracts and block groups)
        formerly surveyed via the decennial census long-form sample. '
      data_source: American Community Survey
      date_last_updated: 12/2020
      summary: 'This dataset contains ACS 5y estimates for selected economic characteristics
        of the population. Topics include income, employment, occupation, commuting
        to work, etc. The data are available at a range of geographic levels in Washington
        and within the 4-county PSRC region (King, Kitsap, Pierce, and Snohomish Counties):
        state, county, CDP (census designated place), and city.

        For more information, please visit the ACS Design and Methodology Report (https://www2.census.gov/programs-surveys/acs/methodology/design_and_methodology/acs_design_methodology_report_2014.pdf)'
      fields:
      - description: ACS survey year
        title: census_year
      - description: A code unique to each geography_type and geography_name
        title: variable_name
      - description: The variable label provides a full logical hierarchy describing
          the entity or entities reflected in the estimate.  Colons separate the items
          in the hierarchy.
        title: variable_label
      - description: The right-most element of the label, i.e. the specific definition
          of the entities summarized in the estimate.
        title: variable_description
      - description: The size or scale of the geographic unit for which the summary
          is provided
        title: geography_type
      - description: Detailed name of geographic area described by geography type
        title: geography_name
      - description: (no description)
        title: estimate
      - description: (no description)
        title: margin_of_error
      - description: (no description)
        title: estimate_percent
      - description: (no description)
        title: margin_of_error_percent
      - description: (no description)
        title: ObjectId
      organization_name: Puget Sound Regional Council
      psrc_website: https://www.psrc.org/american-community-survey-2015-2019-five-year-estimates
      summary_footer: ''
      supplemental_info: 'The 2016-2020 American Community Survey (ACS) data generally
        reflect the September 2018 Office of Management and Budget (OMB) delineations
        of metropolitan and micropolitan statistical areas. In certain instances,
        the names, codes, and boundaries of the principal cities shown in ACS tables
        may differ from the OMB delineation lists due to differences in the effective
        dates of the geographic entities.

        Employment and unemployment estimates may vary from the official labor force
        data released by the Bureau of Labor Statistics because of differences in
        survey design and data collection. For guidance on differences in employment
        and unemployment estimates from different sources go to Labor Force Guidance.

        Workers include members of the Armed Forces and civilians who were at work
        last week.

        Industry titles and their 4-digit codes are based on the North American Industry
        Classification System (NAICS). The Census industry codes for 2018 and later
        years are based on the 2017 revision of the NAICS. To allow for the creation
        of multiyear tables, industry data in the multiyear files (prior to data year
        2018) were recoded to the 2017 Census industry codes.

        Beginning in 2017, selected variable categories were updated, including age-categories,
        income-to-poverty ratio (IPR) categories, and the age universe for certain
        employment and education variables. See user note entitled "Health Insurance
        Table Updates" for further details.

        Between 2018 and 2019 the American Community Survey retirement income question
        changed. These changes resulted in an increase in both the number of households
        reporting retirement income and higher aggregate retirement income at the
        national level. For more information: Changes to the Retirement Income Question.

        The categories for relationship to householder were revised in 2019. For more
        information: Revisions to the Relationship to Household item.

        Beginning in data year 2019, respondents to the Weeks Worked question provided
        an integer value for the number of weeks worked. For data years 2008 through
        2018, respondents selected a category corresponding to the number of weeks
        worked.

        Occupation titles and their 4-digit codes are based on the Standard Occupational
        Classification (SOC). The Census occupation codes for 2018 and later years
        are based on the 2018 revision of the SOC. To allow for the creation of the
        multiyear tables, occupation data in the multiyear files (prior to data year
        2018) were recoded to the 2018 Census occupation codes.

        In 2019, methodological changes were made to the class of worker question.
        These changes involved modifications to the question wording, the category
        wording, and the visual format of the categories on the questionnaire. For
        more information: 2016 American Community Survey Content Test Report for Class
        of Worker.

        The 2015-2019 American Community Survey (ACS) data generally reflect the September
        2018 Office of Management and Budget (OMB) delineations of metropolitan and
        micropolitan statistical areas. In certain instances, the names, codes, and
        boundaries of the principal cities shown in ACS tables may differ from the
        OMB delineation lists due to differences in the effective dates of the geographic
        entities.

        Estimates of urban and rural populations, housing units, and characteristics
        reflect boundaries of urban areas defined based on Census 2010 data. As a
        result, data for urban and rural areas from the ACS do not necessarily reflect
        the results of ongoing urbanization.'
      summary_addendum: 'ACS Handbook for Data Users: https://www.census.gov/programs-surveys/acs/guidance/handbooks.html

        ACS Technical Documentation: https://www.census.gov/programs-surveys/acs/technical-documentation.html

        ACS Data Profiles: https://www.census.gov/acs/www/data/data-tables-and-tools/data-profiles/2020/ '
      time_period: 2016-2020
      update_cadence: Every year
    share_level: everyone
    snippet: null
    groups: PSRC Data Portal Content;hub- Economy;hub- Census & Demographics
    spatial_data: False
    tags: Employment;Income;Population;Census;ACS;ACS5yr;
    title: Economic_Characteristics_From_ACS_2020_5-year_Data_Profiles
  source:
    is_simple: false
    feature_dataset: ''
    has_donut_holes: false
    schema_name: null
    sql_query: select * from data_portal.census_data_profile(2020, 'acs5', 'DP03')
    table_name: null