dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: The data contained in this product are based on the Census 2010
        sample. The data summarized from these files are estimates of the actual figures
        that would have been obtained from a complete count. Estimates derived from
        the census sample files are expected to differ from the100-percent figures
        because they are subject to sampling and nonsampling errors. Sampling error
        in data arises from the selection of people and housing units included in
        the sample. Nonsampling error affects both sample and 100-percent data and
        is introduced as a result of errors that may occur during the data collection
        and processing phases of the census. This chapter provides a detailed discussion
        of both types of errors and a description of the estimation procedures.In
        the Public Use Microdata Samples (PUMS), the basic unit is an individual housing
        unit and the people who live in occupied housing units or group quarters.
        However, microdata records in these samples do not contain names or addresses.
      contact_city: Seattle
      contact_email: Eclute@psrc.org
      contact_name: Eric Clute
      contact_phone: 206-971-3284
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: The Census Bureau defines PUMAs for the tabulation and dissemination
        of decennial census and American Community Survey (ACS) Public Use Microdata
        Sample (PUMS) data. Additionally, the ACS and Puerto Rico Community Survey
        use them to disseminate their respective period estimates.
      data_source: U.S. Census Bureau
      date_last_updated: 04/2022
      description: 'Public Use Microdata Areas (PUMAs) are non-overlapping, statistical
        geographic areas that partition each state or equivalent entity into geographic
        areas containing no fewer than 100,000 people each. They cover the entirety
        of the United States, Puerto Rico, Guam, and the U.S. Virgin Islands. '
      fields:
      - description: Internal feature number
        title: OBJECTID
      - description: (no description)
        title: chng_type
      - description: (no description)
        title: eff_date
      - description: (no description)
        title: relate
      - description: PUMA name.
        title: name
      - description: 2010 Decennial population of PUMA
        title: pop10
      - description: Part flag
        title: partflg
      - description: Vintage
        title: vintage
      - description: (no description)
        title: z_min
      - description: (no description)
        title: z_max
      - description: State FIPS code
        title: statefp10
      - description: 5-character PUMA ID
        title: pumace10
      - description: Old PUMA ID left over from delineation process
        title: pumaold
      - description: Area of feature
        title: Shape_STAr
      - description: Perimeter of feature
        title: Shape_STLe
      psrc_website: ''
      summary_purpose: 
      supplemental_info: 'The delineation of new PUMAs occurs after the completion
        of the decennial census as part of a program involving the State Data Centers
        (SDCs). Decennial census population counts and updated census tracts are critical
        inputs into the delineation process.

        Each microdata file is a 10-percent systematic sample of the full census population.
        Sampling was done address-by-address in order to allow the study of family
        relationships and housing unit characteristics for occupied and vacant units.
        Sampling of people in institutions and other group quarters was done on a
        person-by-person basis.'
      tech_note_link: https://usa.ipums.org/usa/resources/codebooks/2010_PUMS_codebook.pdf
      time_period: 2010-2019
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    tags: Geographic Boundaries;Census;PUMA;
    title: pumas_2010
