macroeconomic_population:
  layer_params:
    tags: macroeconomic forecast population regional
    allow_edits: False
    spatial_data: False
    share_level: everyone
    description: Regional population forecasts from the macroeconomic model
  source:
    schema_name: macroeconomic
    table_name: v_pop

macroeconomic_employment:
  layer_params:
    tags: macroeconomic forecast employment regional
    allow_edits: False
    spatial_data: False
    share_level: everyone
    description: Regional employment forecasts from the macroeconomic model
  source:
    schema_name: macroeconomic
    table_name: v_employment

macroeconomic_households:
  layer_params:
    tags: macroeconomic forecast households regional
    allow_edits: False
    spatial_data: False
    share_level: everyone
    description: Regional households forecasts from the macroeconomic model
  source:
    schema_name: macroeconomic
    table_name: v_households

macroeconomic_income:
  layer_params:
    tags: macroeconomic forecast income regional
    allow_edits: False
    spatial_data: False
    share_level: everyone
    description: Regional income forecasts from the macroeconomic model
  source:
    schema_name: macroeconomic
    table_name: v_income
