dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: ''
      contact_city: Seattle
      contact_email: gsimonson@psrc.org
      contact_name: Gary Simonson
      contact_phone: 206-971-3276
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: The data was collected by the Joint Transportation Committee and
        consultants from jurisdictions
      data_source: Joint Transportation Committee 2016 Road-Rail Conflict Study
      date_last_updated: 01/2016
      description: The At-Grade Rail Crossings dataset highlights the location of
        2,180 roadway/railway crossings across the state that are active, public and
        at-grade.
      fields:
      - description: (no description)
        title: OBJECTID
      - description: (no description)
        title: USDOT_NUMB
      - description: (no description)
        title: CROSSING_S
      - description: (no description)
        title: LAST_INSPE
      - description: (no description)
        title: UTC_NUMBER
      - description: (no description)
        title: UTCSortNum
      - description: (no description)
        title: CROSSING_T
      - description: (no description)
        title: CATEGORY
      - description: (no description)
        title: CITY_NAME
      - description: (no description)
        title: COUNTY_NAM
      - description: (no description)
        title: LATITUDE
      - description: (no description)
        title: LONGITUDE
      - description: (no description)
        title: SECTIONTOW
      - description: (no description)
        title: ROADWAY
      - description: (no description)
        title: IN_CITY_LI
      - description: (no description)
        title: HIGHWAY_MI
      - description: (no description)
        title: STATE_DIST
      - description: (no description)
        title: ROADWAY_TY
      - description: (no description)
        title: STATE_SYST
      - description: (no description)
        title: HIGHWAY
      - description: (no description)
        title: ROAD_SURFA
      - description: (no description)
        title: ROAD_GRADE
      - description: (no description)
        title: ROAD_GRA_1
      - description: (no description)
        title: NUMBER_OF_
      - description: (no description)
        title: F__OF_TRUC
      - description: (no description)
        title: ROAD_TYPE
      - description: (no description)
        title: AADT
      - description: (no description)
        title: AADT_YEAR_
      - description: (no description)
        title: VEHICLE_SP
      - description: (no description)
        title: ROAD_WIDTH
      - description: (no description)
        title: AVERAGE_DA
      - description: (no description)
        title: SCHOOL_BUS
      - description: (no description)
        title: ROAD_DESIG
      - description: (no description)
        title: RAILROAD_C
      - description: (no description)
        title: LINE
      - description: (no description)
        title: BRANCH
      - description: (no description)
        title: RAILROAD_M
      - description: (no description)
        title: IS_SPUR_TR
      - description: (no description)
        title: SPUR_LOCAT
      - description: (no description)
        title: SPUR_IDENT
      - description: (no description)
        title: HAS_ALTERN
      - description: (no description)
        title: BIKE_LANE
      - description: (no description)
        title: COMMERCIAL
      - description: (no description)
        title: HIGH_SPEED
      - description: (no description)
        title: Column2
      - description: (no description)
        title: CROSSING_1
      - description: (no description)
        title: CROSSING_A
      - description: (no description)
        title: TRUCK_PULL
      - description: (no description)
        title: SIDEWALK
      - description: (no description)
        title: EMERGENCY_
      - description: (no description)
        title: OTHER_SURF
      - description: (no description)
        title: WAYSIDE_HO
      - description: (no description)
        title: NUMBER_O_2
      - description: (no description)
        title: POWER_OFF_
      - description: (no description)
        title: ACTIVE_ADV
      - description: (no description)
        title: NUMBER_O_3
      - description: (no description)
        title: CIRCUIT_OV
      - description: (no description)
        title: EVENT_RECO
      - description: (no description)
        title: GATE_DELAY
      - description: (no description)
        title: TRAIN_DETE
      - description: (no description)
        title: INTERCONNE
      - description: (no description)
        title: SWITCH_CUT
      - description: (no description)
        title: STICK_RELE
      - description: (no description)
        title: NUMBER_O_4
      - description: (no description)
        title: CANTILEVER
      - description: (no description)
        title: FOUR_QUADR
      - description: (no description)
        title: ADVANCE_WA
      - description: (no description)
        title: ADVANCE__1
      - description: (no description)
        title: ADVANCE__2
      - description: (no description)
        title: ADVANCE__3
      - description: (no description)
        title: MEDIAN_BAR
      - description: (no description)
        title: MEDIAN_B_1
      - description: (no description)
        title: MEDIAN_B_2
      - description: (no description)
        title: MEDIAN_B_3
      - description: (no description)
        title: STOP_LINES
      - description: (no description)
        title: STOP_LIN_1
      - description: (no description)
        title: STOP_LIN_2
      - description: (no description)
        title: STOP_LIN_3
      - description: (no description)
        title: STOP_LINE_
      - description: (no description)
        title: STOP_LINE1
      - description: (no description)
        title: EAST
      - description: (no description)
        title: WEST
      - description: (no description)
        title: SIDING_TRA
      - description: (no description)
        title: Comments
      - description: (no description)
        title: Down_A_Str
      - description: (no description)
        title: NUMBER_O_5
      - description: (no description)
        title: JTC_STUDY
      - description: (no description)
        title: OIL_COAL_T
      - description: (no description)
        title: INTERSECTI
      - description: (no description)
        title: PASSENGER_
      - description: (no description)
        title: LEGISLATIV
      - description: (no description)
        title: RTPO
      - description: (no description)
        title: MPA
      - description: (no description)
        title: TMA
      - description: (no description)
        title: RrID
      - description: (no description)
        title: OBJECTID_1
      - description: (no description)
        title: MAINLINE
      - description: (no description)
        title: USDOT_NU_2
      - description: (no description)
        title: L1_RR_Clas
      - description: (no description)
        title: L1_SC_Rail
      - description: (no description)
        title: FREIGHT_1
      - description: (no description)
        title: L1_SC_Frei
      - description: (no description)
        title: FREIGHT_2
      - description: (no description)
        title: L1_SC_Fr_1
      - description: (no description)
        title: COMMODITY_
      - description: (no description)
        title: L1_Unit_Tr
      - description: (no description)
        title: PASSENGER1
      - description: (no description)
        title: L1_SC_Pass
      - description: (no description)
        title: PASSENGE_1
      - description: (no description)
        title: L1_SC_Pa_1
      - description: (no description)
        title: AADT_1
      - description: (no description)
        title: L1_SC_Vehi
      - description: (no description)
        title: AADT_2
      - description: (no description)
        title: L1_SC_Ve_1
      - description: (no description)
        title: L1_SCORE_M
      - description: (no description)
        title: L1_Previou
      - description: (no description)
        title: L1_SC_PREV
      - description: (no description)
        title: FUNCTION_C
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: summary purpose
      supplemental_info: ''
      tech_note_link: ''
      time_period: '2016'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Trucks;Traffic/Congestion;Bridges;Freight;Rail;
    title: at_grade_rail_crossings
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: AG_CROSSINGS_STEP1
