dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Since the release of the Census 2000 versions of the TIGER/Line
        files, the Census Bureau has shifted and reshaped most linear features, including
        those that form legal or statistical area boundaries.

        The boundary information in the TIGER/Line Shapefiles is for statistical data
        collection and tabulation purposes only. Their depiction and designation for
        statistical purposes does not constitute a determination of jurisdictional
        authority or rights of ownership or entitlement and they are not legal land
        descriptions. Coordinates in the TIGER/Line shapefiles have six implied decimal
        places, but the positional accuracy of these coordinates is not as great as
        the six decimal places suggest.

        BGs have a valid code range of 0 through 9.  BGs coded 0 were intended to
        only include water area, no land area, and they are generally in territorial
        seas, coastal water, and Great Lakes water areas.  For Census 2000, rather
        than extending a census tract boundary into the Great Lakes or out to the
        U.S. nautical three-mile limit, the Census Bureau delineated some census tract
        boundaries along the shoreline or just offshore.  The Census Bureau assigned
        a default census tract number of 0 and BG of 0 to these offshore, water-only
        areas not included in regularly numbered census tract areas.'
      constraints: null
      contact_city: Seattle
      contact_email: dhanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3272
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: The TIGER/Line Files are shapefiles and related database files
        (.dbf) that are an extract of selected geographic and cartographic information
        from the U.S. Census Bureau`s Master Address File / Topologically Integrated
        Geographic Encoding and Referencing (MAF/TIGER) Database (MTDB). The MTDB
        represents a seamless national file with no overlaps or gaps between parts,
        however, each TIGER/Line File is designed to stand alone as an independent
        data set, or they can be combined to cover the entire nation.
      data_source: U.S. Census Bureau
      date_last_updated: 11/2021
      description: 'Block groups are clusters of blocks within the same census tract
        that have the same first digit of their 4-character census block number from
        the same decennial census.

        Block groups delineated for the 2000 Census generally contain between 600
        and 3,000 peoplee, with an optimum size of 1,500 people. Local participants
        delineated most block groups as part of the Census Bureau`s Participant Statistical
        Areas Program (PSAP). The Census Bureau delineated block groups only where
        a local or tribal government declined to participate or where the Census Bureau
        could not identify a potential local participant.

        A block group usually covers a contiguous area. Each census tract contains
        at least one block group and block groups are uniquely numbered within census
        tract. Within the standard census geographic hierarchy, block groups never
        cross county or census tract boundaries, but may cross the boundaries of county
        subdivisions, places, urban areas, voting districts, congressional districts,
        and American Indian, Alaska Native, and Native Hawaiian areas.'
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: OBJECTID
      - description: (no description)
        title: id
      - description: (no description)
        title: fipsstco
      - description: 2000 Census census tract code
        title: tract
      - description: 2000 Census block group number
        title: group_
      - description: 2000 Census block group identifier; a concatenation of the current
          state FIPS code, county FIPS code, census tract code, and block group number.
        title: stfid
      - description: (no description)
        title: area
      - description: (no description)
        title: perimeter
      - description: (no description)
        title: acres
      - description: (no description)
        title: sq_miles
      - description: (no description)
        title: ochuacre
      - description: (no description)
        title: tract_bg
      - description: (no description)
        title: stf_str
      - description: (no description)
        title: stf2
      - description: (no description)
        title: wlktime_1
      - description: (no description)
        title: trtime_1
      - description: (no description)
        title: wdist_1
      - description: (no description)
        title: pwt_1
      - description: (no description)
        title: wlktime_2
      - description: (no description)
        title: trtime_2
      - description: (no description)
        title: wdist_2
      - description: (no description)
        title: pwt_2
      - description: Default total area of the polygon's perimeter (meters)
        title: Shape__Area
      - description: Default total length of the polygon's perimeter (meters)
        title: Shape__Length
      organization_name: PSRC
      psrc_website: ''
      summary_purpose: 
      supplemental_info: ''
      tech_note_link: 'Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tiger2k/tiger2k.pdf'
      time_period: 2000-2009
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Geographic Boundaries;Census; Block Groups;
    title: block_groups_2000
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: false
    schema_name: null
    sql_query: select Shape.STAsText() as Shape_wkt,  OBJECTID, left(fipsstco, 2)
      as statefp00, right(fipsstco, 3) as countyfp00, case fipsstco when '53053' then
      'Pierce' when '53033' then 'King' when '53035' then 'Kitsap' when '53061' then
      'Snohomish' end as countyname, tract as tract00, group_ as bg00, tract_bg as
      tract_bg00, stfid as geoid00, acres from dbo.blockgrp2000_land_only
    table_name: null
