dataset:
  layer_params:
    accessInformation: 'This dataset contains ACS 1y estimates for selected economic
      characteristics of the population. Topics include income, employment, occupation,
      commuting to work, etc. The data are available at a range of geographic levels
      in Washington and within the 4-county PSRC region (King, Kitsap, Pierce, and
      Snohomish Counties): state, county, MSA (metropolitan statistical area), and
      city with population of 65,000+.'
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Data are based on a sample and are subject to sampling variability.
        The degree of uncertainty for an estimate arising from sampling variability
        is represented through the use of a margin of error (MOE). The value shown
        here is the 90% MOE. The MOE can be interpreted roughly as providing a 90%
        probability that the interval defined by the estimate minus the MOE and the
        estimate plus the MOE (the lower and upper confidence bounds) contains the
        true value. In addition to sampling variability, the ACS estimates are subject
        to nonsampling error (Accuracy of the Data: https://www2.census.gov/programs-surveys/acs/tech_docs/accuracy/ACS_Accuracy_of_Data_2019.pdf).
        The effect of nonsampling error is not represented in these tables.

        Employment and unemployment estimates may vary from the official labor force
        data released by the Bureau of Labor Statistics because of differences in
        survey design and data collection. For guidance on differences in employment
        and unemployment estimates from different sources go to Labor Force Guidance.

        Workers include members of the Armed Forces and civilians who were at work
        last week.

        Industry titles and their 4-digit codes are based on the North American Industry
        Classification System (NAICS). The Census industry codes for 2018 and later
        years are based on the 2017 revision of the NAICS. To allow for the creation
        of multiyear tables, industry data in the multiyear files (prior to data year
        2018) were recoded to the 2017 Census industry codes.

        Beginning in 2017, selected variable categories were updated, including age-categories,
        income-to-poverty ratio (IPR) categories, and the age universe for certain
        employment and education variables. See user note entitled "Health Insurance
        Table Updates" for further details.

        2019 ACS data products include updates to several categories of the existing
        means of transportation question. For more information: Change to Means of
        Transportation.

        Between 2018 and 2019 the American Community Survey retirement income question
        changed. These changes resulted in an increase in both the number of households
        reporting retirement income and higher aggregate retirement income at the
        national level. For more information: Changes to the Retirement Income Question.

        The categories for relationship to householder were revised in 2019. For more
        information: Revisions to the Relationship to Household item.

        Beginning in data year 2019, respondents to the Weeks Worked question provided
        an integer value for the number of weeks worked. For data years 2008 through
        2018, respondents selected a category corresponding to the number of weeks
        worked.

        Occupation titles and their 4-digit codes are based on the Standard Occupational
        Classification (SOC). The Census occupation codes for 2018 and later years
        are based on the 2018 revision of the SOC. To allow for the creation of the
        multiyear tables, occupation data in the multiyear files (prior to data year
        2018) were recoded to the 2018 Census occupation codes.

        In 2019, methodological changes were made to the class of worker question.
        These changes involved modifications to the question wording, the category
        wording, and the visual format of the categories on the questionnaire. For
        more information: 2016 American Community Survey Content Test Report for Class
        of Worker.

        The 2015-2019 American Community Survey (ACS) data generally reflect the September
        2018 Office of Management and Budget (OMB) delineations of metropolitan and
        micropolitan statistical areas. In certain instances, the names, codes, and
        boundaries of the principal cities shown in ACS tables may differ from the
        OMB delineation lists due to differences in the effective dates of the geographic
        entities.

        Estimates of urban and rural populations, housing units, and characteristics
        reflect boundaries of urban areas defined based on Census 2010 data. As a
        result, data for urban and rural areas from the ACS do not necessarily reflect
        the results of ongoing urbanization.'
      constraints: this text should be in resource:Constraints:General:Use Limitations
      contact_city: Seattle
      contact_email: new planner
      contact_name: new planner
      contact_phone: 'new planner'
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'The American Community Survey (ACS) is a survey conducted by
        the U.S. Census Bureau. It uses a series of monthly samples to produce annually
        updated estimates for the same small areas (census tracts and block groups)
        formerly surveyed via the decennial census long-form sample

        For more information, please visit the ACS Design and Methodology Report (https://www2.census.gov/programs-surveys/acs/methodology/design_and_methodology/acs_design_methodology_report_2014.pdf)'
      data_source: American Community Survey
      date_last_updated: 10/2020
      description: 'This dataset contains ACS 1y estimates for selected economic characteristics
        of the population. Topics include income, employment, occupation, commuting
        to work, etc. The data are available at a range of geographic levels in Washington
        and within the 4-county PSRC region (King, Kitsap, Pierce, and Snohomish Counties):
        state, county, MSA (metropolitan statistical area), and city with population
        of 65,000+.'
      fields:
      - description: ACS survey year
        title: census_year
      - description: A code unique to each geography_type and geography_name
        title: variable_name
      - description: The variable label provides a full logical hierarchy describing
          the entity or entities reflected in the estimate.  Colons separate the items
          in the hierarchy.
        title: variable_label
      - description: The right-most element of the label, i.e. the specific definition
          of the entities summarized in the estimate.
        title: variable_description
      - description: The size or scale of the geographic unit for which the summary
          is provided
        title: geography_type
      - description: Detailed name of geographic area described by geography type
        title: geography_name
      - description: (no description)
        title: estimate
      - description: (no description)
        title: margin_of_error
      - description: (no description)
        title: estimate_percent
      - description: (no description)
        title: margin_of_error_percent
      - description: (no description)
        title: ObjectId
      organization_name: PSRC
      psrc_website: https://www.psrc.org/american-community-survey-2019-one-year-estimates
      summary_purpose: summary purpose
      tech_note_link: 'ACS Handbook for Data Users: https://www.census.gov/programs-surveys/acs/guidance/handbooks.html

        ACS Technical Documentation: https://www.census.gov/programs-surveys/acs/technical-documentation.html'
      time_period: '2019'
      update_cadence: Every year
    share_level: everyone
    snippet: null
    spatial_data: false
    tags: Employment;Income;Population;
    title: acs_1_year_dp03
  source:
    is_simple: false
    schema_name: null
    sql_query: select * from data_portal.census_data_profile(2019, 'acs1', 'DP03')
    table_name: null
