dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Since the release of the Census 2000 versions of the TIGER/Line
        files, the Census Bureau has shifted and reshaped most linear features, including
        those that form legal or statistical area boundaries.

        The TIGER/Line Files are shapefiles and related database files (.dbf) that
        are an extract of selected geographic and cartographic information from the
        U.S. Census Bureau`s Master Address File / Topologically Integrated Geographic
        Encoding and Referencing (MAF/TIGER) Database (MTDB). The MTDB represents
        a seamless national file with no overlaps or gaps between parts, however,
        each TIGER/Line File is designed to stand alone as an independent data set,
        or they can be combined to cover the entire nation.'
      contact_city: Seattle
      contact_email: dhanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3271
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'Census blocks, the smallest geographic area for which the Bureau of 
        the Census collects and tabulates decennial census data, are formed by streets, 
        roads, railroads, streams and other bodies of water, other visible physical and 
        cultural features, and the legal boundaries shown on Census Bureau maps.
      
        Census 2000 blocks are numbered uniquely within the 2010 boundaries of each
        state/county/census tract with a 4-character census block number. The first
        character of the tabulation block number identifies the block group.'
      data_source: U.S. Census Bureau
      date_last_updated: 11/2021
      description: Census block boundaries for 2020
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: OBJECTID
      - description: 2020 Census state FIPS code
        title: statefp
      - description: 2020 Census county FIPS code
        title: countyfp
      - description: County in which the census block is located
        title: countyname
      - description: 2020 Census tract code
        title: tractce
      - description: 2020 Census tabulation block number
        title: blockce
      - description: Census block identifier; a concatenation of 2020 Census state
          FIPS code, 2020 Census county FIPS code, 2020 Census tract code, and 2020
          Census block number
        title: geoid20
      - description: 2020 Census tabulation block name; a concatenation of 'Block'
          and the tabulation block number
        title: name
      - description: MAF/TIGER feature class code (G5040)
        title: mtfcc
      - description: 2020 Census urban/rural indicator
        title: funcstat
      - description: 2020 Census urban area code
        title: aland
      - description: 2020 Census funtional status
        title: awater
      - description: 2020 Census land area (meters)
        title: alandmi
      - description: 2020 Census water area (meters)
        title: awatermi
      - description: 2020 Census latitude of the internal point
        title: intptlat
      - description: 2020 Census longitude of the internal point
        title: intptlon
      - description: X coordinate of the centroid (decimal degrees)
        title: xcoord
      - description: Y coordinate of the centroid (decimal degrees)
        title: ycoord
      - description: (no description)
        title: shape_leng
      - description: (no description)
        title: acres
      - description: Default total area of the polygon's perimeter (meters)
        title: Shape__Area
      - description: Default total length of the polygon's perimeter (meters)
        title: Shape__Length
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: 'Estimates of urban and rural populations, housing units,
        and characteristics reflect boundaries of urban areas defined based on Census
        2010 data. As a result, data for urban and rural areas from the ACS do not
        necessarily reflect the results of ongoing urbanization.

        The boundary information in the TIGER/Line Shapefiles is for statistical data
        collection and tabulation purposes only. Their depiction and designation for
        statistical purposes does not constitute a determination of jurisdictional
        authority or rights of ownership or entitlement and they are not legal land
        descriptions. Coordinates in the TIGER/Line shapefiles have six implied decimal
        places, but the positional accuracy of these coordinates is not as great as
        the six decimal places suggest.

        A block number can only be unique by using the decennial census state, county,
        census tract, and block or STATEFP20 + COUNTYFP20 + TRACTCE20 + BLOCKCE20.
        There is no consistency in block numbers from census to census.

        A common misunderstanding is that data users think census blocks are used
        geographically to build all other census geographic areas, rather all other
        census geographic areas are updated and then used as the primary constraints,
        along with roads and water features, to delineate the tabulation blocks.  As
        a result, all 2020 Census blocks nest within every other 2020 Census geographic
        area, so that Census Bureau statistical data can be tabulated at the block
        level and aggregated up to the appropriate geographic areas.'
      tech_note_link: 'Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2020/TGRSHP2020_TechDoc.pdf'
      time_period: 2020-2029
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Census & Demographics
    spatial_data: True
    tags: Geographic Boundaries;Census; Blocks;
    title: Census_Blocks_2020
  source:
    feature_dataset: census
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: 
    table_name: block2020_nowater

