dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Since the release of the Census 2000 versions of the TIGER/Line
        files, the Census Bureau has shifted and reshaped most linear features, including
        those that form legal or statistical area boundaries. '
      contact_city: Seattle
      contact_email: dhanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3270
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: may encompass hundreds of square miles. Census blocks cover all
        territory in the United States, Puerto Rico, and the Island areas. Blocks
        are the smallest geographic areas for which the Census Bureau publishes data
        from the decennial census. A block may consist of one or more faces.
      data_source: U.S. Census Bureau
      date_last_updated: 11/2021
      description: Census block boundaries for 2010
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: OBJECTID
      - description: 2010 Census state FIPS code
        title: statefp10
      - description: 2010 Census county FIPS code
        title: countyfp10
      - description: 2010 Census tract code
        title: tractce10
      - description: 2010 Census tabulation block number
        title: blockce10
      - description: Census block identifier; a concatenation of 2010 Census state
          FIPS code, 2010 Census county FIPS code, 2010 Census tract code, and 2010
          Census block number
        title: geoid10
      - description: 2010 Census tabulation block name; a concatenation of 'Block'
          and the tabulation block number
        title: name10
      - description: MAF/TIGER feature class code (G5040)
        title: mtfcc10
      - description: 2010 Census urban/rural indicator
        title: ur10
      - description: 2010 Census urban area code
        title: uace10
      - description: 2010 Census funtional status
        title: funcstat10
      - description: 2010 Census land area (meters)
        title: aland10
      - description: 2010 Census water area (meters)
        title: awater10
      - description: 2010 Census latitude of the internal point
        title: intptlat10
      - description: 2010 Census longitude of the internal point
        title: intptlon10
      - description: 2010 Census population by block
        title: block_pop
      - description: (no description)
        title: taz_pop
      - description: (no description)
        title: taz_id
      - description: (no description)
        title: totarea
      - description: (no description)
        title: place
      - description: (no description)
        title: juris
      - description: (no description)
        title: juris_type
      - description: X coordinate of the centroid (decimal degrees)
        title: centr_x
      - description: Y coordinate of the centroid (decimal degrees)
        title: cntr_y
      - description: (no description)
        title: acres
      - description: Default total area of the polygon's perimeter (meters)
        title: Shape__Area
      - description: Default total length of the polygon's perimeter (meters)
        title: Shape__Length
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: 'The boundary information in the TIGER/Line Shapefiles is
        for statistical data collection and tabulation purposes only. Their depiction
        and designation for statistical purposes does not constitute a determination
        of jurisdictional authority or rights of ownership or entitlement and they
        are not legal land descriptions. Coordinates in the TIGER/Line shapefiles
        have six implied decimal places, but the positional accuracy of these coordinates
        is not as great as the six decimal places suggest.

        A block number can only be unique by using the decennial census state, county,
        census tract, and block or STATEFP10 + COUNTYFP10 + TRACTCE10 + BLOCKCE10.
        There is no consistency in block numbers from census to census.

        A common misunderstanding is that data users think census blocks are used
        geographically to build all other census geographic areas, rather all other
        census geographic areas are updated and then used as the primary constraints,
        along with roads and water features, to delineate the tabulation blocks.  As
        a result, all 2010 Census blocks nest within every other 2010 Census geographic
        area, so that Census Bureau statistical data can be tabulated at the block
        level and aggregated up to the appropriate geographic areas.'
      tech_note_link: 'Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2010/TGRSHP10SF1.pdf'
      time_period: 2010-2019
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Census & Demographics
    spatial_data: True
    tags: Geographic Boundaries;Census; Blocks;
    title: Census_Blocks_2010
  source:
    feature_dataset: census
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: 
    table_name: block2010_nowater
