dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Since the release of the Census 2000 versions of the TIGER/Line
        files, the Census Bureau has shifted and reshaped most linear features, including
        those that form legal or statistical area boundaries.

        The boundary information in the TIGER/Line Shapefiles is for statistical data
        collection and tabulation purposes only. Their depiction and designation for
        statistical purposes does not constitute a determination of jurisdictional
        authority or rights of ownership or entitlement and they are not legal land
        descriptions. Coordinates in the TIGER/Line shapefiles have six implied decimal
        places, but the positional accuracy of these coordinates is not as great as
        the six decimal places suggest.'
      contact_city: Seattle
      contact_email: dhanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3275
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage:
      data_source: U.S. Census Bureau
      date_last_updated: 11/2021
      summary: "Census tracts are small, relatively permanent geographic entities within counties (or the statistical equivalents of counties) delineated by a committee of local data users. Generally, census tracts have between 2,500 and 8,000 residents and boundaries that follow visible features. When first established, census tracts are to be as homogeneous as possible with respect to population characteristics, economic status, and living conditions."
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: OBJECTID
      - description: (no description)
        title: id
      - description: (no description)
        title: fipsstco
      - description: 2000 Census census tract code
        title: trt2000
      - description: Census tract identifier; a concatenation of Current state FIPS
          code, county FIPS code, and census tract code
        title: stfid
      - description: (no description)
        title: tract_id
      - description: (no description)
        title: source_thm
      - description: (no description)
        title: area
      - description: (no description)
        title: perimeter
      - description: (no description)
        title: acres
      - description: (no description)
        title: z_do
      - description: (no description)
        title: tract_dec
      - description: (no description)
        title: dif7080
      - description: (no description)
        title: diff8090
      - description: (no description)
        title: diff9000
      - description: (no description)
        title: hectares
      - description: (no description)
        title: pct_median
      - description: Default total area of the polygon's perimeter (meters)
        title: Shape__Area
      - description: Default total length of the polygon's perimeter (meters)
        title: Shape__Length
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_footer: ''
      supplemental_info: The TIGER/Line Files are shapefiles and related database
        files (.dbf) that are an extract of selected geographic and cartographic information
        from the U.S. Census Bureau`s Master Address File / Topologically Integrated
        Geographic Encoding and Referencing (MAF/TIGER) Database (MTDB). The MTDB
        represents a seamless national file with no overlaps or gaps between parts,
        however, each TIGER/Line File is designed to stand alone as an independent
        data set, or they can be combined to cover the entire nation.
      summary_addendum: 'Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tiger2k/tiger2k.pdf'
      time_period: 2000-2009
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Census & Demographics
    spatial_data: True
    tags: Geographic Boundaries;Census; Tracts;
    title: Census_Tracts_2000
  source:
    feature_dataset: census
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: 
    table_name: tract2000_nowater