dataset:
  layer_params:
    title: acs_5_year_dp05
    tags: portal, census, acs
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Data Profile 5 from the ACS  5-Year Summaries
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: Data Profile 5 from the Census American Community Survey 5-Year Summaries
        data_source: 
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: Census Data Profiles
  source:
    is_simple: False
    schema_name: 
    table_name: 
    sql_query: select * from data_portal.census_data_profile(2019, 'acs5', 'DP05')