dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      use_constraints: 'Since the release of the Census 2000 versions of the TIGER/Line
        files, the Census Bureau has shifted and reshaped most linear features, including
        those that form legal or statistical area boundaries.

        The boundary information in the TIGER/Line Shapefiles is for statistical data
        collection and tabulation purposes only. Their depiction and designation for
        statistical purposes does not constitute a determination of jurisdictional
        authority or rights of ownership or entitlement and they are not legal land
        descriptions. Coordinates in the TIGER/Line shapefiles have six implied decimal
        places, but the positional accuracy of these coordinates is not as great as
        the six decimal places suggest.

        BGs have a valid code range of 0 through 9.  BGs coded 0 were intended to
        only include water area, no land area, and they are generally in territorial
        seas, coastal water, and Great Lakes water areas.'
      contact_city: Seattle
      contact_email: dhanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3274
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'Block groups delineated for the 2010 Census generally contain
        between 600 and 3,000 people. Local participants delineated most block groups
        as part of the Census Bureau`s Participant Statistical Areas Program (PSAP).
        The Census Bureau delineated block groups only where a local or tribal government
        declined to participate or where the Census Bureau could not identify a potential
        local participant.

        A block group usually covers a contiguous area. Each census tract contains
        at least one block group and block groups are uniquely numbered within census
        tract. Within the standard census geographic hierarchy, block groups never
        cross county or census tract boundaries, but may cross the boundaries of county
        subdivisions, places, urban areas, voting districts, congressional districts,
        and American Indian, Alaska Native, and Native Hawaiian areas.'
      data_source: U.S. Census Bureau
      date_last_updated: 11/2021
      summary: Block Group boundaries for 2020. Block groups are clusters of blocks
        within the same census tract that have the same first digit of their 4-character
        census block number from the same decennial census.
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: OBJECTID
      - description: 2020 Census state FIPS code
        title: statefp
      - description: 2020 Census county FIPS code
        title: countyfp
      - description: County in which the census block group is located
        title: countyname
      - description: 2020 Census census tract code
        title: tractce
      - description: 2020 Census block group number
        title: blkgrpce
      - description: 2020 Census block group identifier; a concatenation of the current
          state FIPS code, county FIPS code, census tract code, and block group number.
        title: geoid20
      - description: 2020 Census translated legal/statistical area description and
          the block group number
        title: namelsad
      - description: MAF/TIGER feature class code (G5030)
        title: mtfcc
      - description: 2020 Census functional status
        title: funcstat
      - description: 2020 Census land area
        title: aland
      - description: 2020 Census water area
        title: awater
      - description: (no description)
        title: alandmi
      - description: (no description)
        title: awatermi
      - description: 2020 Census latitude of the internal point
        title: intptlat
      - description: 2020 Census longitude of the internal point
        title: intptlon
      - description: X coordinate of the centroid (decimal degrees)
        title: xcoord
      - description: Y coordinate of the centroid (decimal degrees)
        title: ycoord
      - description: (no description)
        title: shape_leng
      - description: (no description)
        title: acres
      - description: Default total area of the polygon's perimeter (meters)
        title: Shape__Area
      - description: Default total length of the polygon's perimeter (meters)
        title: Shape__Length
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_footer: ''
      supplemental_info: 'Block groups delineated for the 2010 Census generally contain
        between 600 and 3,000 people. Local participants delineated most block groups
        as part of the Census Bureau`s Participant Statistical Areas Program (PSAP).
        The Census Bureau delineated block groups only where a local or tribal government
        declined to participate or where the Census Bureau could not identify a potential
        local participant. '
      summary_addendum: 'Technical Documentation: https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2020/TGRSHP2020_TechDoc.pdf'
      time_period: 2020-2029
      update_cadence: Every 10 years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Census & Demographics
    spatial_data: True
    tags: Geographic Boundaries;Census; Block Groups;
    title: Census_Block_Groups_2020
  source:
    feature_dataset: census
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: 
    table_name: blockgrp2020_nowater