dataset:
  layer_params:
    title: cities_test
    tags: portal
    allow_edits: False
    spatial_data: True
    share_level: owner
    snippet: cities geospatial data
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The region's cities and towns
        data_source: This data was derived from Source X, published by Agency Y.
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: County-level estimates of different race groups
        fields:
          city_name: name of city
          city_fips: the fips code for the city
  source:
    is_simple: true
    schema_name: dbo
    table_name: cities
    sql_query: 

