dataset:
  layer_params:
    accessInformation: The Park and Ride database contains data on approximately 220
      park and ride locations in the Puget Sound region. This dataset includes the
      name and address of the park and ride, yearly capacity, occupancy and utilization
      rate data and the data source for each of the locations that are surveyed.
    allow_edits: false
    licenseInfo: some text here
    metadata:
      assessment: There are a number of lots that are reported by multiple agencies
        - often with slightly different capacity and/or utilization numbers depending
        on the date of the count. The datasets from King County Metro and Sound Transit
        include the most overlap. When there are overlapping lots, the counts are
        updated based on the values provided by King County, Kitsap, Pierce, and Community
        before Sound Transit is considered.
      constraints: There are a number of lots that are reported by multiple agencies
        - often with slightly different capacity and/or utilization numbers depending
        on the date of the count. The datasets from King County Metro and Sound Transit
        include the most overlap. When there are overlapping lots, the counts are
        updated based on the values provided by King County, Kitsap, Pierce, and Community
        before Sound Transit is considered.
      contact_city: Seattle
      contact_email: mrichards@psrc.org
      contact_name: Mary Richards
      contact_phone: (206)464-7536
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste 500
      contact_zip: 98104
      data_lineage: The park and ride capacity and occupancy data are supplied by
        each of the transit agencies. The collection and reporting system varies by
        agency. Community Transit provides annual counts for capacity and utilized
        parking spaces. King County Metro Transit provides annual capacity counts
        and monthly averages for the number of utilized parking spaces. Kitsap Transit
        provides counts for the capacity and utilized spaces at inconsistent intervals
        (ranging 1-5 times a month), as well as annual averages. Pierce Transit provides
        annual capacity counts and monthly, quarterly, and yearly averages for the
        number of utilized parking spaces. Sound Transit provides monthly counts for
        capacity and utilized parking spaces.
      data_source: Community Transit, King County Metro Transit, Kitsap Transit, Pierce
        Transit, and Sound Transit
      date_last_updated: Mar-21
      description: The Park and Ride database contains data on approximately 220 park
        and ride locations in the Puget Sound region. This dataset includes the name
        and address of the park and ride, yearly capacity, occupancy and utilization
        rate data and the data source for each of the locations that are surveyed.
      organization_name: PSRC
      psrc_website: www.psrc.org
      summary_purpose: summary purpose
      fields:
        - title: city_name
          description: name of city
        - title: city_fips
          description: the fips code for the city
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Commuting and Travel Habits;Parking;Transit and Ferries
    title: cities_test
  source:
    is_simple: false
    schema_name: n/a
    sql_query: select * from some_table
    table_name: n/a