dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      use_constraints: ''
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: '206-971-3269 '
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: The cities shapefile includes geographic boundaries for all cities
        located in King, Snohomish, Pierce, and Kitsap counties. This dataset also
        includes VISION 2050 regional geography classifications.
      data_source: Puget Sound Regional Council
      date_last_updated: 12/2024
      summary: The city boundaries are updated on a quarterly basis using annexation
        information from OFM (https://ofm.wa.gov/washington-data-research/annexations-and-municipal-boundary-changes).
        VISION 2050 regional geography classifications were added to the dataset in
        2020.
      fields:
      - description: Name of city
        title: city_name
      - description: Name of county
        title: cnty_name
      - description: Federal Information Processing Standard Publication ID for city
        title: city_fips
      - description: Federal Information Processing Standard Publication ID for county
        title: cnty_fips
      - description: Geography type assigned by PSRC
        title: feat_type
      - description: VISION 2050 regional geography ID
        title: rgeo_class
      - description: VISION 2050 regional geography description
        title: class_desc
      - description: Acreage
        title: acres_gis
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_footer: ''
      supplemental_info: ''
      summary_addendum: ''
      time_period: '2024'
      update_cadence: Quarterly
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content
    spatial_data: True
    tags: Geographic Boundaries;Cities;
    title: Cities_points7
  source:
    feature_dataset: political
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: cities_points
