dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    groups: 'hub- GIS;hub- Transportation;PSRC Data Portal Content'
    licenseInfo: null
    metadata:
      assessment: N/A
      contact_city: Seattle
      contact_email: mkoch@psrc.org
      contact_name: Mitch Koch
      contact_phone: '206-464-7537 '
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'The CTR worksites survey data was provided by WSDOT CTR Program
        (contact: Michael Wandler). The survey data is collected by WSDOT from the
        participating CTR worksites every two years. WDOT provided the data in excel,
        as well as geographic data in GIS shapefiles.'
      data_source: WSDOT
      date_last_updated: 11/2019
      description: The Commute Trip Reduction (CTR) Worksites dataset contains the
        locations of CTR worksites in the Region and the mode share of trips for each
        worksite. These are worksites are participating in WSDOT`s CTR program based
        on several requirements. These worksites implement CTR strategies and provide
        survey data to WSDOT to track their CTR implementation strategies and progress.
        This dataset is based on the 2017-2018 survey data.
      fields:
      - description: unique record identifier
        title: FID *
      - description: County
        title: County_Name
      - description: local jurisdiction (city, etc.)
        title: Jurisdicti
      - description: unique CTR worksite identifier for each record
        title: CTRID
      - description: Organization name of worksite
        title: Organizati
      - description: Name of building/ worksite, if applicable
        title: Worksite
      - description: Survey close date
        title: SurveyClos
      - description: If Sampling (Was the survey a sample or total population
        title: Expansion_F
      - description: 'Number of returned surveys divided by the number of distributed
          surveys '
        title: Response_Ra
      - description: 'Total count of Employees at site '
        title: Total_Emplo
      - description: 'Surveys Distributed unless the survey was a Sampled site, and
          then it is multiplied by the expansion factor '
        title: Expanded_Su
      - description: 'Number of records received for survey unless the survey was
          a Sampled site, and then it is multiplied by the expansion factor '
        title: Expanded_1
      - description: 'No Fill Vehicle Miles Traveled per employee data '
        title: VMT_per_Empl
      - description: 'Total Vehicle Miles Traveled for Worksite '
        title: Total_VMT
      - description: 'Non-drive alone rate: Add the drive alone trips to the 1 person
          motorcycle trips and divide by the total weekly trips'
        title: NDAT_Rate
      - description: Annual GHG per employee in metric tons
        title: Total_Annua
      - description: 'Annual VMT calculated out to daily and converted to Pounds from
          metric tons '
        title: Daily_GHG_pe
      - description: Total Weekly Count Trips
        title: Total_Weekl
      - description: Weekly Drive Alone Trips
        title: Weekly_Driv
      - description: Weekly Carpool Trips multiplied by an expansion factor
        title: Weekly_Carp
      - description: Weekly Vanpool Trips multiplied by an expansion factor
        title: Weekly_Vanp
      - description: 'Weekly 1 person Motorcycle Trips multiplied by an expansion
          factor '
        title: Weekly_Moto
      - description: 'Weekly 2 person Motorcycle Trips multiplied by an expansion
          factor '
        title: Weekly_Mo_1
      - description: 'Weekly Bus Trips multiplied by an expansion factor '
        title: Weekly_BusT
      - description: 'Weekly Train/Lightrail/Street Car Trips multiplied by an expansion
          factor '
        title: Weekly_Trai
      - description: Weekly Bike Trips multiplied by an expansion factor
        title: Weekly_Bike
      - description: 'Weekly Walk Trips multiplied by an expansion factor '
        title: Weekly_Walk
      - description: Weekly Telework Trips multiplied by an expansion factor
        title: Weekly_Tele
      - description: 'Weekly CWW Trips multiplied by an expansion factor '
        title: Weekly_CWWD
      - description: Weekly Overnight Business Trips multiplied by an expansion factor
        title: Weekly_Over
      - description: Weekly Did Not Work Trips multiplied by an expansion factor
        title: Weekly_DidN
      - description: 'Weekly Boarded Ferry with Car/Bus/Van Trips multiplied by an
          expansion factor '
        title: Weekly_Ferr
      - description: Weekly Ferry as Walk on Passenager Trips multiplied by an expansion
          factor
        title: Weekly_Fe_1
      - description: Weekly Other Trips multiplied by an expansion factor
        title: Weekly_Othe
      - description: Weekly Drive Alone Trips divided by Total Weekly Count Trips
        title: Drive_Alone
      - description: 'Weekly Carpool Trips divided by Total Weekly Count Trips '
        title: Carpool_Sha
      - description: Weekly Vanpool Trips divided by Total Weekly Count Trips
        title: Van_Share
      - description: (Weekly 1 Person Motorcycle Trips plus Weekly 2 Person Motorcycle
          Trips) divided by Total Weekly Count Trips
        title: Motorcycle
      - description: 'Weekly Bus Trips divided by Total Weekly Count Trips '
        title: Bus_Share
      - description: Weekly Train/Lightrail/Street Car Trips divided by Total Weekly
          Count Trips
        title: Train_Share
      - description: Weekly Bike Trips divided by Total Weekly Count Trips
        title: Bike_Share
      - description: Weekly Walk Trips divided by Total Weekly Count Trips
        title: Walk_Share
      - description: Weekly Telework Trips divided by Total Weekly Count Trips
        title: Telework_Sh
      - description: 'Weekly CWW Trips divided by Total Weekly Count Trips '
        title: CWW_Share
      - description: Weekly Boarded Ferry with Car/Bus/Van Trips plus Weekly Used
          Ferry as Walk-on Passenager Trips divided by Total Weekly Count Trips
        title: Ferry_WalkO
      - description: Weekly Boarded Ferry with Car/Bus/Van Trips plus Weekly Used
          Ferry as Drive-on Trips divided by Total Weekly Count Trips
        title: Ferry_Drive
      - description: Weekly Other Trips divided by Total Weekly Count Trips
        title: Other_Share
      - description: (no description)
        title: GlobalID
      - description: Worksite Status within the system at time of survey (affected,
          voluntary, unaffected)
        title: Status
      - description: Uses Survey Close date to determine which cycle
        title: Survey_Cycl
      - description: Latitude
        title: Latitude
      - description: Longitude
        title: Longitude
      - description: Baseline survey
        title: Baseline
      - description: (no description)
        title: Shape *
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: ''
      time_period: 2017-2018
      update_cadence: As needed
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Traffic/Congestion;Employment;
    title: Commute_Trip_Reduction_Worksites
  source:
    feature_dataset: transportation_tdm
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: ctr_work_sites_region