parking_inventory_status:
  layer_params:
    title: parking_inventory_status
    tags: regional, parking, test
    allow_edits: False
    spatial_data: False
    share_level: everyone
    description: Regional airport layer
    snippet: This should be a very short description of the data.
    accessInformation: The person to appear under the credits in AGOL
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: test contact name
        contact_email: testname@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        abstract: This is a sample abstract, or short summary of the data.
        data_source: This data was derived from Source X, published by Agency Y.
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: 'This should go in Resource:Details:Description:Summary(Purpose)'
  source:
    is_simple: true
    schema_name: parking_inventory
    table_name: status_dim
    sql_query: select status_dim_id, status_code, status_name from parking_inventory.status_dim

