dataset:
  layer_params:
    accessInformation: This shapefile includes boundaries for all counties in the
      state of Washington.
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: The information contained herein was developed for general regional
        land use and transportation planning purposes. The users of this information
        must determine its suitability for any other purpose. Some of this data may
        have been compiled from other sources. The PSRC does not accept responsibility
        for the quality of third-party data or data contributed by others. Locations
        of all facilities are approximate.
      constraints: The information contained herein was developed for general regional
        land use and transportation planning purposes. The users of this information
        must determine its suitability for any other purpose. Some of this data may
        have been compiled from other sources. The PSRC does not accept responsibility
        for the quality of third-party data or data contributed by others. Locations
        of all facilities are approximate.
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3269
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: nan
      data_source: Puget Sound Regional Council
      date_last_updated: 04/2018
      description: This shapefile includes boundaries for all counties in the state
        of Washington.
      fields:
      - description: (no description)
        title: perimeter
      - description: (no description)
        title: county_cod
      - description: Federal Information Processing Standard Publication ID for county
        title: county_fip
      - description: County name
        title: county_name
      - description: A 1 denotes a PSRC county and a 0 denotes a non-PSRC county
        title: psrc
      psrc_website: www.psrc.org
      summary_purpose: summary purpose
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Geographic Boundaries;
    title: county_background
  source:
    is_simple: true
    schema_name: n/a
    sql_query: null
    table_name: COUNTY_BACKGROUND
