dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'Refer to Technical Documentation: https://www.psrc.org/sites/default/files/displacementrisk.pdf'
      contact_city: Seattle
      contact_email: blee@psrc.org
      contact_name: Brian Lee
      contact_phone: 206-971-3270
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'Data collected from American Community Survey (ACS), U.S. Census
        Bureau; Consolidated Housing Affordability Strategy (CHAS), U.S. Department
        of Housing & Urban Development (HUD); Google; County elections data; Puget
        Sound Regional Council. '
      data_source: Puget Sound Regional Council
      date_last_updated: '2018'
      description: 'Displacement risk is a composite of indicators representing five
        elements of neighborhood displacement risks: socio-demographics, transportation
        qualities, neighborhood characteristics, housing, and civic engagement. The
        data from these five displacement indicators were compiled into a comprehensive
        index of displacement risk for all census tracts in the region. Refer to Technical
        Documentation: https://www.psrc.org/sites/default/files/displacementrisk.pdf'
      fields:
      - description: this is a shapefile field for census tract data
        title: FID
      - description: this is a shapefile field for census tract data
        title: OBJECTID
      - description: this is a shapefile field for census tract data
        title: statefp10
      - description: this is a shapefile field for census tract data
        title: countyfp10
      - description: this is a shapefile field for census tract data
        title: tractce10
      - description: this is a shapefile field for census tract data
        title: geoid10
      - description: this is a shapefile field for census tract data
        title: name10
      - description: this is a shapefile field for census tract data
        title: namelsad10
      - description: this is a shapefile field for census tract data
        title: mtfcc10
      - description: this is a shapefile field for census tract data
        title: funcstat10
      - description: this is a shapefile field for census tract data
        title: aland10
      - description: this is a shapefile field for census tract data
        title: awater10
      - description: this is a shapefile field for census tract data
        title: intptlat10
      - description: this is a shapefile field for census tract data
        title: intptlon10
      - description: this is a shapefile field for census tract data
        title: name_val
      - description: this is a shapefile field for census tract data
        title: sq_miles
      - description: this is a shapefile field for census tract data
        title: acres
      - description: this is a shapefile field for census tract data
        title: geoidstr
      - description: this is a shapefile field for census tract data
        title: perc
      - description: this is a shapefile field for census tract data
        title: perc_1
      - description: 11-digit census tract number
        title: tract_geoi
      - description: (no description)
        title: risk_score
      - description: category of displacement risk - number
        title: risk_level
      - description: category of displacement risk - name
        title: risk_name
      - description: this is a shapefile field for census tract data
        title: Shape__Area
      - description: this is a shapefile field for census tract data
        title: Shape__Length
      organization_name: Puget Sound Regional Council
      psrc_website: https://www.psrc.org/displacement-risk-mapping
      summary_purpose: ''
      supplemental_info: 'Data collected from American Community Survey (ACS), U.S.
        Census Bureau; Consolidated Housing Affordability Strategy (CHAS), U.S. Department
        of Housing & Urban Development (HUD); Google; County elections data; Puget
        Sound Regional Council. '
      tech_note_link: 'Technical documentation: https://www.psrc.org/sites/default/files/displacementrisk.pdf'
      time_period: '2018'
      update_cadence: Periodically
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Equity
    spatial_data: True
    tags: Equity; Census;Displacement Risk
    title: Displacement_Risk_2018
  source:
    feature_dataset: 'equity'
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: displacement_2018
