dataset:
  layer_params:
    title: covered_employment_by_city_by_major_sector
    tags: portal, employment
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Covered employment by city by major sector
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: Covered employment data by city by major sector
        data_source: Our employment summaries derive from the Quarterly Census of Employment and Wages (QCEW), administrative records employers report, by law, to the Washington State Employment Security Department (ESD).  To provide more accurate workplace reporting, PSRC gathers supplemental data from the Boeing Company, the Office of Washington Superintendent of Public Instruction (OSPI), and governmental units throughout the central Puget Sound region.
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: Data collected from the periodic Regional Parking Inventory 
  source:
    is_simple: True
    schema_name: employment_summaries
    table_name: v_covered_employment_by_city_by_major_sector
    sql_query:
