dataset:
  layer_params:
    title: equity_tracts_2016
    tags: portal, census
    allow_edits: False
    spatial_data: True
    share_level: everyone
    snippet: 
    accessInformation: 
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        assessment: 
        constraints: 
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        data_source: 
        date_last_updated: 
        data_lineage: 
        description: TBD
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        summary_purpose: 
        tech_note_link: 
        time_period: '2016'
        update_cadence: As needed
  source:
    is_simple: false
    schema_name: 
    table_name:  
    sql_query: "select * from Elmer.data_portal.equity_tracts(2016)"