dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: Boundaries extend into the water rather than adhere to the shoreline.  Therefore
        for zones with shoreline the areas don`t represent land areas and are inappropriate
        to use for density or other area-based calculations.
      constraints: null
      contact_city: Seattle
      contact_email: koverby@psrc.org
      contact_name: Kris Overby
      contact_phone: 206-464-6661
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: The 2000 FAZs are aggregations of 2000 TAZs and also 1990 Census
        Tracts.  The FAZs are similar in structure to the 2010 FAZs with some boundary
        differences due to the 2010 Block geography used for 2010 FAZs.  The 2000
        FAZs were constructed by PSRC staff with input by member jurisdictions.
      data_source: Puget Sound Regional Council
      date_last_updated: '2002'
      description: FAZ 2000 - Forecast Analysis Zones boundaries.  These are aggregations
        of TAZs and ther are 219 of them in the 4-county region.  FAZs are the units
        of the geographic boundary system used by PSRC to model and report its small
        area Forecasts of Population, Households, and Employment.
      fields:
      - description: FAZ number
        title: faz
      - description: 'appears to be # of TAZs within FAZ'
        title: count
      - description: area (square feet)
        title: area
      - description: perimeter (feet)
        title: perimeter
      - description: area (acres)
        title: acres
      - description: area (hectares)
        title: hectares
      - description: global_id
        title: global_id
      - description: area (square feet) - redundant
        title: Shape__Area
      - description: perimeter (feet) - redundant
        title: Shape__Length
      organization_name: PSRC
      psrc_website: ''
      summary_purpose: 
      supplemental_info: ''
      tech_note_link: The boundaries for this FAZ shapefile extend out into the water.  For
        display and calculation purposes it would be better to create another version
        that has its boundaries clipped at the shoreline, although there is probably
        limited demand for this file at this point in time.  Also be aware that although
        the number of FAZs didn`t change (219) from FAZ 2000 to FAZ 2010, the boundaries
        changed for some zones due to the transition from TAZ 2000 to TAZ 2010 geographies.
      time_period: 2002-2011
      update_cadence: Periodically
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Employment;Geographic Boundaries;Population;Modeling;
    title: faz_2000
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: faz2000
