dataset:
  layer_params:
    title: household_travel_survey_days
    tags: portal, household travel survey
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Days table from PSRC's Household Travel Survey, years 2017 and 2019
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Days table from the combined 2017 and 2019 Household Travel Survey
        data_source: PSRC's 2017 and 2019 Household Travel Survey work
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: 
  source:
    is_simple: True
    schema_name: hhsurvey
    table_name: v_days_2017_2019_public
    sql_query:
