dataset:
  layer_params:
    title: household_travel_survey_days
    tags: portal, household travel survey
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Days table from PSRC's Household Travel Survey, years 2017, 2019 and 2021
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Days table from the combined 2017, 2019 and 2021 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: '2022'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        tech_note_link:
        time_period: "2017 - 2021"
        update_cadence: Roughly every two years
  source:
    is_simple: True
    schema_name: hhsurvey
    table_name: v_days
    sql_query:
