dataset:
  layer_params:
    title: Household_Travel_Survey_Households
    tags: portal, household travel survey
    allow_edits: False
    groups: PSRC Data Portal Content;Household Travel Survey Content
    spatial_data: False
    share_level: everyone
    snippet: Households table from PSRC's Household Travel Survey, years 2017, 2019, 2021 and 2023
    accessInformation: 
    licenseInfo:
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1201 3rd Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Households table from the combined 2017, 2019, 2021 and 2023 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: '2024'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        supplemental_info: ''
        tech_note_link:
        time_period: "2017 - 2023"
        update_cadence: Roughly every two years
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name: 
    sql_query: "select  [household_id],
    [hhgroup], [traveldate_start], [traveldate_end], [numdayscomplete], [hh_is_complete], [num_days_complete_weekday], [num_complete_mon], [num_complete_tue],
    [num_complete_wed], [num_complete_thu], [num_complete_fri], [num_days_complete_weekend], [num_complete_sat], [num_complete_sun], [num_trips], [hhsize],
    [num_surveyable], [num_participants], [numadults], [numchildren], [numworkers], [num_students], [vehicle_count], [hhincome_detailed],
    [hhincome_followup], [hhincome_broad], [psrc], [home_tract20], [home_jurisdiction], [home_rgcname], [home_uvnum], [home_county], [res_type],
    [rent_own], [res_months], [res_dur], [prev_rent_own], [prev_res_type], [prev_home_rgcname], [prev_home_jurisdiction], [prev_home_tract20], 
    [prev_home_county], [prev_home_wa], [prev_home_notwa_state], [prev_home_notwa_city],
    [prev_home_notwa_zip], [prev_res_factors_housing_cost], [prev_res_factors_income_change], [prev_res_factors_community_change], 
    [prev_res_factors_hh_size], [prev_res_factors_more_space], [prev_res_factors_less_space], [prev_res_factors_employment],
    [prev_res_factors_amenities], [prev_res_factors_telework], [prev_res_factors_school], [prev_res_factors_crime], 
    [prev_res_factors_quality], [prev_res_factors_forced], [prev_res_factors_other], [prev_res_factors_no_answer],
    [prev_res_factors_specify], [broadband], [survey_year], [hh_race_category], [hh_weight] 
from HHSurvey.v_households_labels"
