dataset:
  layer_params:
    title: Household_Travel_Survey_Vehicles
    tags: portal, household travel survey
    allow_edits: False
    groups: PSRC Data Portal Content;Household Travel Survey Content
    spatial_data: False
    share_level: everyone
    snippet: Version 2023.4 of the Vehicles table from PSRC's Household Travel Survey, years 2017, 2019, 2021 and 2023
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1201 3rd Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Vehicles table from the combined 2017, 2019, 2021 and 2023 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: 'December 2024'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        supplemental_info: ''
        tech_note_link:
        time_period: "2017 - 2023"
        update_cadence: Roughly every two years
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name:
    sql_query: "select 
          [vehicle_id], [household_id], [vehnum], [make], [model], [model_other], [year], [fuel], [toll_transponder], [survey_year]
      from HHSurvey.v_vehicles_labels"
