dataset:
  layer_params:
    title: Household_Travel_Survey_Households
    tags: portal, household travel survey
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Households table from PSRC's Household Travel Survey, years 2017, 2019 and 2021
    accessInformation: 
    licenseInfo:
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Households table from the combined 2017, 2019 and 2021 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: '2022'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        tech_note_link:
        time_period: "2017 - 2021"
        update_cadence: Roughly every two years
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name: 
    sql_query: "SELECT [household_id]
        ,[hhid] ,[hhgroup] ,[survey_year] ,[seattle_home] ,[sample_county] ,[final_home_puma10]
        ,[final_home_uvnum] ,[dayofweek], [hhsize] ,[vehicle_count] ,[lifecycle] ,[hhincome_broad] ,[hhincome_detailed]
        ,[hh_race_category] ,[car_share] ,[rent_own] ,[res_dur] ,[res_type] ,[prev_home_wa]
        ,[prev_home_puma10] ,[prev_home_seattle] ,[res_factors_30min] ,[res_factors_afford] ,[res_factors_closefam] ,[res_factors_cultural]
        ,[res_factors_hhchange] ,[res_factors_hwy] ,[res_factors_school] ,[res_factors_space] ,[res_factors_transit] ,[res_factors_walk]
        ,[prev_res_factors_housing_cost] ,[prev_res_factors_income_change] ,[prev_res_factors_community_change] ,[prev_res_factors_hh_size] ,[prev_res_factors_more_space] ,[prev_res_factors_less_space]
        ,[prev_res_factors_employment] ,[prev_res_factors_school] ,[prev_res_factors_crime] ,[prev_res_factors_quality] ,[prev_res_factors_forced] ,[prev_res_factors_no_answer]
        ,[prev_res_factors_other] ,[prev_res_factors_specify] ,[prev_res_factors_covid_flexibility] ,[prev_res_factors_covid_health] ,[broadband] ,[final_home_tract]
        ,[cityofseattle] ,[home_city_name] ,[res_factors_displaced] ,[numadults] ,[numchildren] ,[numworkers]
        ,[offpark_cost] ,[hh_weight_2021_ABS] ,[hh_weight_2017_v2021] ,[hh_weight_2019_v2021] ,[hh_weight_2017_2019_v2021]
      FROM [Elmer].[HHSurvey].[v_households]"
