dataset:
  layer_params:
    title: Household_Travel_Survey_Persons
    tags: portal, household travel survey
    allow_edits: False
    groups: PSRC Data Portal Content;Household Travel Survey Content
    spatial_data: False
    share_level: everyone
    snippet: Persons table from PSRC's Household Travel Survey, years 2017 and 2019
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1201 3rd Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: 
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The persons table from the combined 2017, 2019 and 2021 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: '2022'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        supplemental_info: ''
        tech_note_link:
        time_period: "2017 - 2021"
        update_cadence: Roughly every two years
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name: 
    sql_query: "SELECT [household_id]
      ,[hhgroup] ,[survey_year] ,[sample_source] ,[seattle_home] ,[hh_race_category], [sample_segment]
      ,[cityofseattle] ,[final_home_puma10] ,[final_home_uvnum] ,[hhsize] ,[vehicle_count] ,[lifecycle]
      ,[hhincome_broad] ,[hhincome_detailed] ,[car_share] ,[rent_own] ,[res_dur] ,[res_type]
      ,[prev_home_wa] ,[res_factors_30min] ,[res_factors_afford] ,[res_factors_closefam] ,[res_factors_hhchange] ,[res_factors_hwy]
      ,[res_factors_school] ,[res_factors_space] ,[res_factors_transit] ,[res_factors_walk] ,[numadults] ,[numchildren]
      ,[numworkers] ,[offpark_cost] ,[prev_res_factors_housing_cost] ,[prev_res_factors_income_change] ,[prev_res_factors_community_change] ,[prev_res_factors_hh_size]
      ,[prev_res_factors_more_space] ,[prev_res_factors_less_space] ,[prev_res_factors_employment] ,[prev_res_factors_school] ,[prev_res_factors_crime] ,[prev_res_factors_quality]
      ,[prev_res_factors_forced] ,[prev_res_factors_no_answer] ,[prev_res_factors_other] ,[prev_res_factors_specify] ,[prev_res_factors_covid_flexibility] ,[prev_res_factors_covid_health]
      ,[broadband] ,[industry] ,[person_id] ,[age] ,[age_category] ,[gender]
      ,[employment] ,[jobs_count] ,[student] ,[schooltype] ,[education] ,[license]
      ,[vehicleused] ,[workplace] ,[race_afam] ,[race_asian] ,[race_hapi] ,[race_aiak]
      ,[race_hisp] ,[race_other] ,[race_white] ,[race_noanswer] ,[race_category] ,[hours_work]
      ,[commute_freq] ,[commute_mode] ,[commute_dur] ,[telecommute_freq] ,[work_park_type] ,[workpass]
      ,[work_county] ,[work_rgcname] ,[prev_work_county] ,[prev_work_puma10], [prev_work_tract10], [prev_work_notwa_state] ,[prev_work_notwa_notus]
      ,[school_loc_county] ,[school_puma10] , [school_tract10], [school_rgcname] ,[mode_freq_1] ,[mode_freq_2] ,[mode_freq_3]
      ,[mode_freq_4] ,[mode_freq_5] ,[tran_pass_1] ,[tran_pass_2] ,[tran_pass_3] ,[tran_pass_4]
      ,[tran_pass_5] ,[tran_pass_6] ,[tran_pass_7] ,[tran_pass_8] ,[tran_pass_9] ,[tran_pass_10]
      ,[tran_pass_11] ,[benefits_1] ,[benefits_2] ,[benefits_3] ,[benefits_4] ,[av_interest_1]
      ,[av_interest_2] ,[av_interest_3] ,[av_interest_4] ,[av_interest_5] ,[av_interest_6] ,[av_interest_7]
      ,[av_concern_1] ,[av_concern_2] ,[av_concern_3] ,[av_concern_4] ,[av_concern_5] ,[wbt_transitmore_1]
      ,[wbt_transitmore_2] ,[wbt_transitmore_3] ,[wbt_bikemore_1] ,[wbt_bikemore_2] ,[wbt_bikemore_3] ,[wbt_bikemore_4]
      ,[wbt_bikemore_5] ,[commute_auto_time] ,[commute_auto_distance] , [work_tract10]
      ,[work_puma10] ,[worker] ,[employment_pre_covid] ,[commute_freq_pre_covid] ,[commute_mode_pre_covid] ,[telecommute_freq_pre_covid]
      ,[school_travel_last_week] ,[employment_change_employer] ,[employment_change_location] ,[employment_change_new_job] ,[employment_change_laid_off] ,[employment_change_left_workforce]
      ,[employment_change_none] ,[workplace_pre_covid] ,[hh_weight_2021] ,[person_adult_weight_2021] ,[person_respondent_weight_2021] ,[hh_weight_2017]
      ,[hh_weight_2019] ,[hh_weight_2017_2019] ,[hh_weight_2017_2019_adult] 
	  FROM [Elmer].[HHSurvey].[v_persons]"