dataset:
  layer_params:
    title: Household_Travel_Survey_Trips
    tags: portal, household travel survey
    allow_edits: False
    groups: PSRC Data Portal Content;Household Travel Survey Content
    spatial_data: False
    share_level: everyone
    snippet: Version 2023.5 of the Trips table from PSRC's Household Travel Survey, years 2017, 2019, 2021 and 2023
    accessInformation: 
    licenseInfo: 
    metadata:
        contact_name: Suzanne Childress
        contact_email: schildress@psrc.org
        contact_street_address: 1201 3rd Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Trips table from the combined 2017, 2019, 2021 and 2023 Household Travel Survey
        data_source: PSRC's Household Travel Survey program
        date_last_updated: 'December 2024'
        constraints: 
        data_lineage: "The Puget Sound Regional Travel Studies collect data across King, Kitsap, Pierce, and Snohomish counties using an online and GPS smartphone app-based survey data approach." 
        assessment: 
        summary_purpose: 
        supplemental_info: ''
        tech_note_link:
        time_period: "2017 - 2023"
        update_cadence: Roughly every two years
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name: 
    sql_query: "select
        [trip_id], [household_id], [person_id], [day_id], [pernum], [daynum], [tripnum], [travel_day],
        [travel_date], [travel_dow], [day_iscomplete], [svy_complete], [depart_date], [depart_dow], [depart_time_hour], [depart_time_minute],
        [depart_time_second], [arrive_date], [arrive_dow], [arrival_time_hour], [arrival_time_minute], [arrival_time_second], [o_in_region], 
        [origin_rgcname], [origin_county], [origin_jurisdiction], [origin_tract10], [origin_tract20], [d_in_region], [dest_rgcname], [dest_county], 
        [dest_jurisdiction], [dest_tract10], [dest_tract20], [distance_meters], [distance_miles],
        [duration_minutes], [duration_seconds], [speed_mph], [speed_flag], [dwell_mins], [days_first_trip], [days_last_trip], [origin_purpose_cat],
        [origin_purpose], [origin_name], [dest_purpose_cat], [dest_purpose], [dest_purpose_other], [dest_name], [mode_class], [mode_1],
        [mode_2], [mode_3], [mode_4], [mode_other_specify], [mode_acc], [mode_egr], [travelers_total], [travelers_hh],
        [travelers_nonhh], [hhmember1], [hhmember2], [hhmember3], [hhmember4], [hhmember5], [hhmember6], [hhmember7],
        [hhmember8], [hhmember9], [hhmember10], [hhmember11], [hhmember12], [driver], [change_vehicles], [taxi_cost_known],
        [taxi_cost_int], [analyst_split], [analyst_merged], [analyst_split_loop], [copied_trip], [user_split], [user_merged], [user_added],
        [flag_teleport], [trace_quality_flag], [pt_density], [point_dist_index], [survey_year], [hh_day_iscomplete], [trip_weight]
      from HHSurvey.v_trips_labels"