dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: ''
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: '206-971-3269 '
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: Center boundaries are provided to PSRC by the relevant jurisdictions.
      data_source: Puget Sound Regional Council
      date_last_updated: 07/20
      description: This shapefile includes boundaries for the ten designated regional
        manufacturing/industrial centers, which are locations for more intensive industrial
        activity. Both regional growth centers and regional manufacturing/industrial
        centers are focal points for planned growth, economic development and transportation
        infrastructure investments. https://www.psrc.org/centers
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: count_
      - description: Name of county where center is located
        title: county_nam
      - description: (no description)
        title: pop00
      - description: (no description)
        title: emp00
      - description: Name of center
        title: mic
      - description: (no description)
        title: shape_leng
      - description: Acreage
        title: acres
      - description: Type of center
        title: category
      organization_name: Puget Sound Regional Council
      psrc_website: https://www.psrc.org/centers
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: 'Regional Centers Framework Update: https://www.psrc.org/sites/default/files/final_regional_centers_framework_march_22_version.pdf'
      time_period: '2021'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Geographic Boundaries;Centers/MICs;Industrial Lands;
    title: Manufacturing_Industrial_Centers
  source:
    feature_dataset: 'political'
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: micen
