dataset:
  layer_params:
    title: military_bases
    tags: portal, military
    allow_edits: False
    spatial_data: True
    share_level: everyone
    snippet: 
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The region's milrary bases
        data_source: Data Source to be added at a later date
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: Reference layer for the region's Military Bases
  source:
    is_simple: false
    schema_name: 
    table_name: 
    sql_query: select OBJECTID, name, Shape.STAsText() as Shape_wkt from dbo.military_bases

