dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: The information contained herein was developed for general regional
        land use and transportation planning purposes. The users of this information
        must determine its suitability for any other purpose. Some of this data may
        have been compiled from other sources. The PSRC does not accept responsibility
        for the quality of third-party data or data contributed by others. Locations
        of all facilities are approximate.
      constraints: this text should be in resource:Constraints:General:Use Limitations
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3269
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: ''
      data_source: Puget Sound Regional Council
      date_last_updated: 01/2017
      description: This layer includes boundary locations for all military bases in
        King, Snohomish, Pierce, and Kitsap counties.
      fields:
      - description: Name of military base
        title: name
      organization_name: PSRC
      psrc_website: ''
      summary_purpose: summary purpose
      supplemental_info: ''
      tech_note_link: ''
      time_period: '2021'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Geographic Boundaries;Military;
    title: military_bases
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: false
    schema_name: null
    sql_query: select OBJECTID, name, Shape.STAsText() as Shape_wkt from dbo.military_bases
    table_name: null
