dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 
      contact_city: Seattle
      contact_email: 
      contact_name: 
      contact_phone:
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 
      data_source: 
      date_last_updated: 
      description: 
      fields:
      organization_name: Puget Sound Regional Council
      psrc_website: 'https://www.psrc.org'
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: ''
      time_period: 
      update_cadence: As needed
    share_level: everyone
    snippet: null
    groups: ''
    spatial_data: false
    tags: 'PSRC'
    title: jurisdiction_dim
  source:
    is_simple: true
    has_donut_holes: false
    schema_name: ofm
    table_name: jurisdiction_dim
    sql_query: 
