dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 
      contact_city: Seattle
      contact_email: blee@psrc.org
      contact_name: Brian Lee
      contact_phone: (206)464-7536
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 
      data_source: American Community Survey
      date_last_updated: 
      summary: 
      fields:
      organization_name: Puget Sound Regional Council
      psrc_website: 'https://www.psrc.org/our-work/rtp '
      summary_footer: ''
      supplemental_info: ''
      summary_addendum: ''
      time_period: 2018
      update_cadence: As needed
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content
    spatial_data: True
    tags: portal,opportunity,equity
    title: Opportunity_Index_Equity_Tracts
  source:
    is_simple: true
    has_donut_holes: true
    feature_dataset: equity
    schema_name: dbo
    table_name: equity_tracts
    sql_query: 
