dataset:
  layer_params:
    title: parking_inventory_by_block_group
    tags: portal, parking
    allow_edits: False
    spatial_data: False
    share_level: everyone
    snippet: Parking inventory summaries by block group
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: Data Profile 2 from the Census American Community Survey 1-Year Summaries
        data_source: 
        date_last_updated: This will ultimately be derived automatically but for the moment is entered in the datasource yml.
        constraints: 'this text should be in resource:Constraints:General:Use Limitations'
        data_lineage: This should be a description of the data collection process?
        assessment: 'This should go in Quality:Data Quality: Report'
        summary_purpose: Data collected from the periodic Regional Parking Inventory 
  source:
    is_simple: True
    schema_name: data_portal
    table_name: v_parking_by_block_group
    sql_query:
