dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: ''
      contact_city: Seattle
      contact_email: gsimonson@psrc.org
      contact_name: Gary Simonson
      contact_phone: 206-971-3276
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: ''
      data_source: Washington State Department of Transportation
      date_last_updated: 02/2021
      description: The Private Truck Parking dataset includes privately-owned truck
        parking facilities, including numbers of stalls and types of amenities included
        on-site.
      fields:
      - description: (no description)
        title: stop_name
      - description: (no description)
        title: name
      - description: (no description)
        title: corridor
      - description: (no description)
        title: lat
      - description: (no description)
        title: long_
      - description: What is the exit number?
        title: exit_
      - description: (no description)
        title: street_add
      - description: (no description)
        title: city
      - description: (no description)
        title: direction
      - description: How many parking spaces?
        title: parking_sp
      - description: Does it have fuel?
        title: fuel
      - description: Does it have restrooms?
        title: restrooms
      - description: Does it have food service?
        title: food_servi
      - description: Does it have showers?
        title: showers
      - description: (no description)
        title: exit_displ
      - description: (no description)
        title: electrific
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: This data is collected by WSDOT
      tech_note_link: ''
      time_period: '2021'
      update_cadence: Every few years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Transportation
    spatial_data: True
    tags: Trucks;Traffic/Congestion;Parking;
    title: Private_Truck_Stops
  source:
    feature_dataset: 'transportation_freight'
    has_donut_holes: true
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: PRIVATE_TRUCK_STOP
