dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      use_constraints: For most current data, it is best to check with individual transit
        agencies
      contact_city: Seattle
      contact_email: jkim@psrc.org
      contact_name: Jean Kim
      contact_phone: 206-971-3052
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 'Transit agencies, except ferry agencies, send information on
        their service district boundaries, as needed to PSRC. Transit districts are
        determined by Public Transit Benefit Areas (PTBAs are granted the authority
        to impose a voter-authorized sales tax), City/County boundaries, and other
        service areas.  The majority of transit systems in the region are operated
        by PTBAs, with the exception of King County Metro and Sound Transit (a regional
        transit authority). '
      data_source: Puget Sound Regional Council
      date_last_updated: '2018'
      summary: The Transit District Boundary layer represents general service
        district boundaries of public transit agencies (except ferry agencies) in
        the central Puget Sound, including Community Transit, Everett Transit, King
        County Metro, Kitsap Transit, Pierce Transit, and Sound Transit.
      fields:
      - description: Unique ID for each field
        title: FID
      - description: Type of shape
        title: Shape
      - description: Area
        title: AREA
      - description: Perimeter
        title: Perimeter
      - description: Layer name
        title: Name
      - description: City ID for each layer
        title: City
      - description: Shape length
        title: Shape_Leng
      - description: Shape area
        title: Shape_Area
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_footer: ''
      supplemental_info: ''
      summary_addendum: ''
      time_period: '2018'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Transportation
    spatial_data: True
    tags: Geographic Boundaries;Transit;
    title: Public_Transportation_Benefit_Areas
  source:
    is_simple: true
    feature_dataset: 'transportation_transit'
    has_donut_holes: true
    schema_name: dbo
    sql_query: 
    table_name: transit_districts