dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: "In general, less rate information was available and collected in 
      2022 than in 2018. This may result in less precise comparisons of rate changes 
      at more detailed geography levels. A greater variation in maximum capacity values 
      was also noted, likely the result of a select areas with concentrated development 
      and new procedures for flagging these records under construction. A wider use of 
      online sources from the 2018 survey helped to identify new major developments and 
      structures in addition to satellite imagery. 

      In 2018 the data collection methodology changed significantly. Occupancy counts were no 
      longer collected and PSRC`s internal staff used alternative methods to collect the 
      capacity and costs information (i.e. departed from physical survey collection and 
      moved towards online collection methods such as google maps, SDOT, etc.). In 2018 
      inventory took advantage of more online data collection strategies and although 
      fieldwork remained a component, slightly different field collection methods were 
      utilized.  To compare the 2013 and 2018 parking inventory data, PSRC tabulated 
      and mapped the absolute and relative differences in the number of parking stalls 
      between the two survey years. The tracts with percent increases or decreases in 
      the number of parking stalls greater than 10% were identified as outliers and 
      further examined at the block level. Ten census tracts had parking growth or decline 
      of more than 10%. After closer investigation, the majority of these changes were 
      due to several reasons. First, in some instances, there were differences in the 
      number of surveyed blocks within the same tracks between 2013 and 2018 data collection. 
      Second, some tracks had new developments and added parking capacity."
      contact_city: Seattle
      contact_email: mrichards@psrc.org
      contact_name: Mary Richards
      contact_phone: 206-464-7090
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: " Prior to 2018, PSRC collected parking facility information every 
      two to five years exclusively through fieldwork. PSRC revised the data collection 
      process in 2018 by designing a new multi-phase approach. The changes include an 
      online research procedure that collects data ahead of fieldwork, the use of Survey123 
      (ArcGIS) to record the data, and the establishment of an ETL (Extract, Transfer, Load) 
      process to structure 2018 amd future inventory within PSRC's central database.

      Data was collected according to updated procedures begun in the 2018 parking survey. 
      The 2022 dataset reflects greater use of online resources and less reliance on field 
      work and direct data collection. Online sources were referenced between late March and 
      July of 2022, with field work conducted June 15-22, 2022. Data also reflects updated 
      2020 census geographies."
      data_source: Puget Sound Regional Council
      date_last_updated: May 2023
      description: The parking Inventory dataset contains the number of parking facilities,
        number of stalls, lot types, and parking costs of off-street parking, public
        and private, free, and pay-to-park facilities. Data are available for cities
        (Bellevue, Bremerton, Everette, Seattle, Tacoma), the University District
        neighborhood, and three ferry terminals (Bainbridge, Kingston, and Southworth).
      fields:
      - description: The year the data was collected
        title: year_of_survey
      - description: Census block group id for the decade corresponding to the year_of_survey date.
        title: block_group_geoid
      - description: The location of the paylot
        title: city
      - description: Number of hourly pay parking lots within the block group
        title: paylots_with_hourly_costs
      - description: Minimum hourly cost
        title: min_cost_hourly
      - description: Maximum hourly cost
        title: max_cost_hourly
      - description: Average cost of hourly parking lots (summed costs/number of paylots
          with hourly costs)
        title: avg_cost_hourly
      - description: Number of daily pay parking lots within the block group
        title: paylots_with_daily_costs
      - description: Minimum daily cost
        title: min_cost_daily
      - description: Maximum daily cost
        title: max_cost_daily
      - description: Average cost of daily parking lots (summed costs/number of paylots
          with daily costs)
        title: avg_cost_daily
      - description: Number of monthly pay parking lots within the block group
        title: paylots_with_monthly_costs
      - description: Minimum monthly cost
        title: min_cost_monthly
      - description: Maximum monthly cost
        title: max_cost_monthly
      - description: Average cost of monthly parking lots (summed costs/number of
          paylots with monthly costs)
        title: avg_cost_monthly
      - description: Sum of the lots within the block group
        title: total_lot_count
      - description: Sum of all parking stalls within the block group
        title: total_stalls
      - description: Total number of cars within the block group in the morning
        title: total_am_car_count
      - description: Total number of cars within the block group in the afternoon
        title: total_pm_car_count
      - description: Average number of parking stalls within the block group
        title: average_total_stalls
      - description: Average number of cars within the block group in the morning
        title: average_am_car_count
      - description: Average number of cars within the block group in the afternoon
        title: average_pm_car_count
      - description: The percent of parking stalls occupied within the block group
          in the morning
        title: am_occupancy_rate
      - description: The percent of parking stalls occupied within the block group
          in the afternoon
        title: pm_occupancy_rate
      - description: The percent of parking stalls occupied within the block group
          (average of AM and PM occupancy rates)
        title: average_daily_occupancy_rate
      - description: (no description)
        title: ObjectId
      organization_name: Puget Sound Regional Council
      psrc_website: https://www.psrc.org/parking-inventory
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: ''
      time_period: 2002-2022
      update_cadence: 2-5 years
    share_level: everyone
    snippet: null
    groups: PSRC Data Portal Content;hub- Transportation
    spatial_data: False
    tags: Parking;
    title: Regional_Parking_Inventory
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: true
    schema_name: data_portal
    sql_query: null
    table_name: v_parking_by_block_group
