dataset:
  layer_params:
    title: regional_bikeped
    tags: Portal, data-portal, bikeped, active transportation
    allow_edits: False
    spatial_data: True
    share_level: everyone
    snippet: 
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Chris Peak
        contact_email: cpeak@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-7536
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: 
        data_source: 
        date_last_updated: 
        constraints: 
        data_lineage: 
        assessment: 
        summary_purpose: 
  source:
    is_simple: false
    schema_name: dbo
    table_name: REGIONAL_BIKEPED 
    sql_query: "select 
	bp.OBJECTID,
	bp.psrc_edge_id,
	bp.facility_type,
	ijpf.[value] as ij_ped_facilities,
	jipf.[value] as ji_ped_facilities,
	bp.sidewalk_notes,
	sws.[value] as sidewalk_source,
	ijbf.[value] as ij_bike_facilities_value,
	jibf.[value] as ji_bike_facilities_value,
	ijbt.[value] as ij_bike_type,
	jibt.[value] as ji_bike_type,
	bp.bike_editor_notes,
	bp.bike_source,
	bp.bike_complete,
	bp.ped_complete,
  bp.Shape.STAsText() as Shape_wkt
from dbo.REGIONAL_BIKEPED bp
	join dbo.fn_domain_values('dPedFacilities') as ijpf on bp.ij_ped_facilities = ijpf.code
	join dbo.fn_domain_values('dPedFacilities') as jipf on bp.ji_ped_facilities = jipf.code
	join dbo.fn_domain_values('dPedFacilities') as ijbf on bp.ij_bike_facilities = ijbf.code
	join dbo.fn_domain_values('dPedFacilities') as jibf on bp.ji_bike_facilities = jibf.code
	join dbo.fn_domain_values('dSideWalkSource') as sws on bp.sidewalk_source = sws.code
	join dbo.fn_domain_values('dBikeLanes') as ijbt on bp.ij_bike_type = ijbt.code
	join dbo.fn_domain_values('dBikeLanes') as jibt on bp.ji_bike_type = jibt.code"

