dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 'The shapefile is based on datasets collected by different agencies,
        so the underlying data collection methodologies differ. Also, the datasets
        were developed between 2015-2020, and so represent different levels of currency. '
      contact_city: Seattle
      contact_email: njohnson@psrc.org
      contact_name: Nick Johnson
      contact_phone: 480-464-7890
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: PSRC used jurisdictional data collected in 2019 and 2020, with
        most datasets produced by the jurisdictions between 2015 and 2019. In cases
        where jurisdictional data was not available or unclear, in 2020 and 2021 PSRC
        also reviewed Google Maps to collect supplementary aerial data.In May 2019,
        PSRC conducted a survey of all jurisdictions in the region to learn whether
        they had available bicycle and/or pedestrian facility data. Based on the survey
        results, PSRC then collected data from jurisdictions with available data,
        including digital or static maps. The collected data was used to code all
        minor and major arterial roadways and shared use paths in the region according
        to the presence, completeness, and type of facilities. In cases where jurisdictional
        data was not available or unclear, PSRC used supplementary data from aerial
        imagery to complete the inventory.
      data_source: Puget Sound Regional Council
      date_last_updated: 04/2021
      description: 'This shapefile documents the existence of pedestrian and bicycle
        facilities on minor and principal arterials in the PSRC region according to
        completeness and facility type. The coding is based on the sidewalk and bicycle
        facility data provided by local jurisdictions in 2019 and 2020, along with
        supplementary data from aerial imagery where jurisdictional data was not available.
        All arterial roadway segments were coded to indicate the presence and completeness
        of facilities on each side of the road (IJ and JI directions). On-road bicycle
        facilities were also coded according to facility type. '
      fields:
      - description: PSRC object ID
        title: OBJECTID*
      - description: 'Internal documentation of PSRC roadway edges (segments); useful
          for referencing in communications to PSRC. '
        title: psrc_edge_id
      - description: Type of roadway (Minor/Principal Arterial)
        title: facility_type
      - description: 'Presence/completeness of pedestrian facilities on one side of
          the street. IJ represents one side of the street. '
        title: ij_ped_facilities
      - description: Presence/completeness of pedestrian facilities on one side of
          the street. JI represents one side of the street.
        title: ji_ped_facilities
      - description: Source of the data for coding pedestrian facilities, either Jurisdiction2020
          (for jurisdictional data) or Aerials2020 (for aerial data)
        title: sidewalk_source
      - description: Presence/completeness of bicycle facilities on one side of the
          street. IJ represents one side of the street.
        title: ij_bike_facilities
      - description: Presence/completeness of bicycle facilities on one side of the
          street. JI represents one side of the street.
        title: ji_bike_facilities
      - description: Type of bicycle facility, if present
        title: ij_bike_type
      - description: Type of bicycle facility, if present
        title: ji_bike_type
      - description: Source of the data for coding bicycle facilities, either Jurisdiction2020
          (for jurisdictional data) or Aerials2020 (for aerial data)
        title: bike_source
      - description: Length of the roadway segment (in feet).
        title: length_ft
      - description: The name of the roadway
        title: fullname
      - description: Length of the roadway segment (in feet).
        title: shape_length
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: 'Please visit the Data Dictionary for more information on this
        facility inventory: https://www.psrc.org/sites/default/files/bikeped2021jan21-2021webmapdatadictionary.pdf'
      time_period: 2015-2020
      update_cadence: Every 4 years
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Transportation
    spatial_data: True
    tags: Bike/Ped;
    title: Regional_Bike_and_Pedestrian_Facilities
  source:
    is_simple: True
    feature_dataset: ''
    has_donut_holes: false
    schema_name: dbo
    sql_query: null
    table_name: REGIONAL_BIKEPED
