dataset:
  layer_params:
    title: regional_sups
    tags: Portal, data-portal, bikeped, active transportation, shared-use paths
    allow_edits: False
    spatial_data: True
    share_level: everyone
    snippet: 
    accessInformation: A Data Science Team Member
    licenseInfo: The text to appear under Terms of Use in AGOL
    metadata:
        contact_name: Kimberly Pearson
        contact_email: kpearson@psrc.org
        contact_street_address: 1011 Western Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98104
        contact_phone: (206)464-5833
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: Shared-use paths in the PSRC Region
        data_source: 
        date_last_updated: 
        constraints: 
        data_lineage: 
        assessment: 
        summary_purpose: 
  source:
    is_simple: true
    schema_name: dbo
    table_name: REGIONAL_SUPS 
    sql_query: 

