dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      use_constraints: The information contained herein was developed for general regional
        land use and transportation planning purposes.  The users of this information
        must determine its suitability for any other purpose.  Some of this data may
        have been compiled from other sources.  The PSRC does not accept responsibility
        for the quality of third-party data or data contributed by others.  Locations
        of all facilities are approximate.
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3269
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: Regional Growth Centers (RGC's) have been defined by the Regional Council
        as "regionally designated locations that are intended to include a dense mix
        of business, commercial, residential, and cultural activities within a compact
        area of up to 1.5 square miles targeted for employment and residential growth,
        a wide variety of transportation options, including fast and convenient high
        capacity transit service, as well as investment in major public amenities."
      data_source: Puget Sound Regional Council
      date_last_updated: 06/2023
      summary: 'This layers represents boundaries for the 29 designated regional
        growth centers in the central Puget Sound region. Each county or city, through
        an inter-jurisdictional process, has designated the center boundaries.

        https://www.psrc.org/centers'
      fields:
      - description: (no description)
        title: FID
      - description: (no description)
        title: id
      - description: Name of regional growth center
        title: name
      - description: (no description)
        title: area_feet
      - description: (no description)
        title: perimeter_
      - description: (no description)
        title: parking
      - description: (no description)
        title: popden1996
      - description: (no description)
        title: planpop96
      - description: (no description)
        title: jobs1994
      - description: (no description)
        title: planjobs94
      - description: (no description)
        title: houseunits
      - description: (no description)
        title: huplan
      - description: (no description)
        title: floorspc
      - description: Acreage
        title: acres
      - description: (no description)
        title: hectares
      - description: (no description)
        title: area
      - description: (no description)
        title: perimeter
      - description: (no description)
        title: adoptdate
      - description: Type of center
        title: category
      organization_name: Puget Sound Regional Council
      psrc_website: https://www.psrc.org/centers
      summary_footer: ''
      supplemental_info: The data was originally assembled from various cities and
        counties in the region. If boundary updates occur, PSRC will receive the updated
        boundary file from the city or county and make updates to this file.
      summary_addendum: https://www.psrc.org/media/3038
      time_period: '2023'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Land Use Data
    spatial_data: True
    tags: Centers/MICs;Geographic Boundaries;
    title: Regional_Growth_Centers
  source:
    feature_dataset: political
    has_donut_holes: false
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: URBAN_CENTERS
