dataset:
  layer_params:
    title: Safety_and_Security
    tags: portal, household travel survey
    allow_edits: False
    groups: PSRC Data Portal Content;Household Travel Survey Content
    spatial_data: False
    share_level: everyone
    snippet: Version 2026.1 of the Safety and Security data as collected as a follow-up project to the 2025 wave of the Household Travel Survey
    accessInformation: 
    licenseInfo:
    metadata:
        contact_name: Brian Lee
        contact_email: blee@psrc.org
        contact_street_address: 1201 3rd Ave. Ste 500
        contact_city: Seattle
        contact_state: Washington
        contact_zip: 98101
        contact_phone: 
        fields:
        organization_name: PSRC
        psrc_website: www.psrc.org
        description: The Safety and Security Survey Data that was done as a follow-up project with the 2025 wave of the Household Travel Survey
        data_source: PSRC's Safety and Security survey
        date_last_updated: 'May 2026'
        constraints: 
        data_lineage: "" 
        assessment: 
        summary_purpose: 
        supplemental_info: ''
        tech_note_link:
        time_period: "2025"
        update_cadence: ??? 
  source:
    is_simple: False
    feature_dataset: ''
    has_donut_holes: false
    schema_name: 
    table_name: 
    sql_query: " 
      SELECT [person_id]
            ,[hhid]
            ,[time_start]
            ,[date_complete]
            ,[complete]
            --,[ip_lon]
            --,[ip_lat]
            ,[enjoy_travel]
            ,[cost_consideration]
            ,[worry]
            ,[dest_proximity]
            ,[satisfied]
            ,[safety_ratings]
            ,[environment_emphasis]
            ,[own_car]
            ,[risk_taking]
            ,[travel_satisfaction]
            ,[safe_option]
            ,[travel_stressful]
            ,[telework_importance]
            ,[transit_travel]
            ,[drive]
            ,[travel_methods_drove]
            ,[travel_methods_rideshare]
            ,[travel_methods_carshare]
            ,[travel_methods_motorcycle]
            ,[travel_methods_transit]
            ,[travel_methods_bicycle]
            ,[travel_methods_e_scooter]
            ,[travel_methods_walk]
            ,[travel_methods_none]
            ,[drive_relax]
            ,[small_car]
            ,[walk_trips]
            ,[physical_close]
            ,[comfortable_test]
            ,[active_transport_practical]
            ,[safe_car_size]
            ,[learn_bike]
            ,[want_learn_bike]
            ,[can_bike]
            ,[bike_confidence]
            ,[res_with_lanes]
            ,[bike_trails]
            ,[want_bike]
            ,[employ]
            ,[employment]
            ,[work_days]
            ,[telework]
            ,[telework_freq]
            ,[commute_freq]
            ,[office_type]
          --   ,[work_loc_1]
          --   ,[work_loc_2]
          --   ,[work_loc_3]
          --   ,[work_loc_4]
          --   ,[work_loc_5]
            ,[commute_mode]
            ,[commute_mode_other]
            ,[transit_freq]
            ,[bike_freq]
            ,[walk_freq]
            ,[tnc_freq]
            ,[motorcycle_freq]
            ,[car_freq]
            ,[caregiver]
            ,[walk_comfort]
            ,[walk_comfort_traffic]
            ,[walk_comfort_infra]
            ,[walk_comfort_comfort]
            ,[walk_comfort_security]
            ,[walk_comfort_maintenance]
            ,[walk_comfort_perception]
            ,[walk_comfort_far]
            ,[walk_comfort_dist]
            ,[walk_comfort_dislike]
            ,[walk_comfort_other]
            ,[walk_comfort_other_specify]
            ,[bike_comfort]
            ,[bike_comfort_traffic]
            ,[bike_comfort_infra]
            ,[bike_comfort_comfort]
            ,[bike_comfort_security]
            ,[bike_comfort_maintenance]
            ,[bike_comfort_perception]
            ,[bike_comfort_far]
            ,[bike_comfort_distance]
            ,[bike_comfort_own]
            ,[bike_comfort_dislike]
            ,[bike_comfort_other]
            ,[bike_comfort_other_specify]
            ,[transit_comfort]
            ,[transit_comfort_traffic]
            ,[transit_comfort_infra]
            ,[transit_comfort_schedule]
            ,[transit_comfort_comfort]
            ,[transit_comfort_comfort_bus]
            ,[transit_comfort_security]
            ,[transit_comfort_perception]
            ,[transit_comfort_mismatch]
            ,[transit_comfort_available]
            ,[transit_comfort_challenge]
            ,[transit_comfort_dislike]
            ,[transit_comfort_other]
            ,[transit_comfort_other_specify]
            ,[neighborhood_trips]
            ,[walk_recreation]
            ,[walk_recreation_comfort]
            ,[bike_recreation]
            ,[bike_recreation_comfort]
            ,[traffic_worry]
            ,[harrassment]
            ,[urgent_worry]
            ,[walk_recreation_relax]
            ,[travel_anxiety]
            ,[overall_safety]
            ,[travel_worry]
            ,[drive_safely]
            ,[bike_comfort_cars]
            ,[alert_traveler]
            ,[drive_worry]
            ,[signal_confidence]
            ,[worry_destination]
            ,[safety_choices]
            ,[safety_choices_costs]
            ,[safety_choices_modes]
            ,[worry_security]
            ,[shortest_path_fear]
            ,[shortest_path_assault]
            ,[traffic_crash_worry]
            ,[traffic_harrassment]
            ,[no_safe_travel]
            ,[no_harm_travel]
            ,[feel_safe]
            ,[fear_assault]
            ,[feel_safe_crash]
            ,[fear_assault_2]
            ,[avoid_walk_1]
            ,[avoid_walk_2]
            ,[system_safe]
            ,[safe_clothes]
            ,[traffic_enforcement]
            ,[speed_limits]
            ,[disagree_test]
            ,[traffic_deaths]
            ,[traffic_rules]
            ,[crash_participant]
            ,[crash_witness]
            ,[crash_near_miss]
            ,[security_concern]
            ,[no_experience]
            ,[no_share]
            ,[experience_followup]
            ,[crash_when]
            ,[crash_mode]
            ,[crash_travelling_other]
            ,[crash_time]
            ,[crash_time_other]
            ,[crash_conditions_clear]
            ,[crash_conditions_cloud]
            ,[crash_conditions_rain]
            ,[crash_conditions_snow]
            ,[crash_conditions_sleet]
            ,[crash_conditions_fog]
            ,[crash_conditions_unknown]
            ,[crash_conditions_other]
            ,[crash_conditions_unsure]
            ,[crash_conditions_pnta]
            ,[crash_conditions_other_specify]
            ,[crash_involved]
            ,[crash_number_people]
            ,[crash_other_mode]
            ,[crash_other_tnc]
            ,[crash_other_motorcycle]
            ,[crash_other_car]
            ,[crash_other_bike]
            ,[crash_other_escooter]
            ,[crash_other_walk]
            ,[crash_other_other]
            ,[crash_other_unsure]
            ,[crash_other_pnta]
            ,[crash_other_specify]
            ,[crash_severity]
            ,[crash_worry_self]
            ,[crash_worry_others]
            ,[crash_change_travel]
            ,[crash_change_time]
            ,[crash_travel_less]
            ,[crash_none]
            ,[crash_share_other]
            ,[crash_share_sentiment]
            ,[near_miss_followup]
            ,[near_miss_when]
            ,[near_miss_mode]
            ,[near_miss_time]
            ,[near_miss_clear]
            ,[near_miss_cloudy]
            ,[near_miss_rain]
            ,[near_miss_snow]
            ,[near_miss_sleet]
            ,[near_miss_fog]
            ,[near_miss_unknown]
            ,[near_miss_other]
            ,[near_miss_unsure]
            ,[near_miss_pnta]
            ,[near_miss_other_specify]
            ,[near_miss_other_party]
            ,[near_miss_num_people]
            ,[near_miss_care]
            ,[near_miss_tnc]
            ,[near_miss_motorcylce]
            ,[near_miss_driving]
            ,[near_miss_bike]
            ,[near_miss_scooter]
            ,[near_miss_walking]
            ,[near_miss_mode_other_party]
            ,[near_miss_mode_unsure]
            ,[near_miss_mode_pnta]
            ,[near_miss_worry_self]
            ,[near_miss_worry_others]
            ,[near_miss_change_travel]
            ,[near_miss_change_time]
            ,[near_miss_travel_less]
            ,[near_miss_none]
            ,[witness_followup]
            ,[witness_when]
            ,[witness_num_people]
            ,[witness_mode_driving]
            ,[witness_mode_tnc]
            ,[witness_mode_motorcycle]
            ,[witness_mode_transit]
            ,[witness_mode_bike]
            ,[witness_mode_scooter]
            ,[witness_mode_walk]
            ,[witness_mode_other]
            ,[witness_mode_unsure]
            ,[witness_mode_pnta]
            ,[witness_mode_other_specify]
            ,[witness_time]
            ,[witness_clear]
            ,[witness_cloud]
            ,[witness_rain]
            ,[witness_snow]
            ,[witness_sleet]
            ,[witness_fog]
            ,[witness_unsure]
            ,[witness_other_condition]
            ,[witness_other_condition_specify]
            ,[witness_severity]
            ,[witness_worry_self]
            ,[witness_worry_others]
            ,[witness_change_travel]
            ,[witness_change_time]
            ,[witness_travel_less]
            ,[witness_none]
            ,[witness_other_specify]
            ,[personal_security_followup]
            ,[security_smoking]
            ,[security_music]
            ,[security_yelling]
            ,[security_touching]
            ,[security_comments]
            ,[security_intimidation]
            ,[security_erratic]
            ,[security_approaching]
            ,[security_lewd]
            ,[security_violence]
            ,[security_property]
            ,[security_other]
            ,[security_other_specify]
            ,[mobility_aides]
            ,[incentive_complete]
            ,[test_q_flag]
            ,[same_answer_count]
            ,[same_answer_prop]
            ,[time_to_complete]
            ,[time_flag]
            ,[rsg_rec]
            ,[race_1]
            ,[race_2]
            ,[race_3]
            ,[race_4]
            ,[race_5]
            ,[race_997]
            ,[race_999]
            ,[gender]
            ,[ethnicity_1]
            ,[ethnicity_2]
            ,[ethnicity_3]
            ,[ethnicity_4]
            ,[ethnicity_997]
            ,[ethnicity_999]
            ,[age]
            --,[home_lon]
            --,[home_lat]
            --,[work_lat]
            --,[work_lon]
            --,[work_loc_flag]
            ,[platform]
            ,[hh_children]
          --   ,[home_loc_1]
          --   ,[home_loc_2]
          --   ,[home_loc_3]
          --   ,[home_loc_4]
          --   ,[home_loc_5]
            ,[home_loc_flag]
          --   ,[invite_lat]
          --   ,[invite_lon]
            ,[witness_severity_other_specify]
            ,[near_miss_mode_other_party_specify]
            ,[near_miss_mode_other_specify]
            ,[race_other_specify]
            ,[hhsize]
            ,[numchildren]
            ,[vehicle_count]
            ,[hhincome_detailed]
            ,[disability_person]
            ,[participate]
            ,[witness_other]
            ,[non_res_streets]
            ,[person_weight]
            ,[commute_fix_flag]
            ,[work_mode]
            ,[sample_segment]
        FROM [Elmer].[safety_survey].[v_responses_2025]
    "