dataset:
  layer_params:
    accessInformation: This dataset includes the location of rest areas in the region,
      including information about parking, restroom, drinking water, and vending facilities.
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: nan
      contact_city: Seattle
      contact_email: gsimonson@psrc.org
      contact_name: Gary Simonson
      contact_phone: 206-971-3276
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: WSDOT collects this data
      data_source: WSDOT
      date_last_updated: 08/2019
      description: This dataset includes the location of rest areas in the region,
        including information about parking, restroom, drinking water, and vending
        facilities.
      fields:
      - description: (no description)
        title: OBJECTID
      - description: (no description)
        title: name
      - description: (no description)
        title: cleaned_name
      - description: (no description)
        title: corridor
      - description: (no description)
        title: lat
      - description: (no description)
        title: long_
      - description: (no description)
        title: milepost
      - description: (no description)
        title: mp_display
      - description: (no description)
        title: location
      - description: (no description)
        title: direction
      - description: (no description)
        title: parking_stall
      - description: (no description)
        title: restroom
      - description: (no description)
        title: drinking_water
      - description: (no description)
        title: vending
      - description: (no description)
        title: 'type '
      - description: (no description)
        title: shape
      psrc_website: nan
      summary_purpose: summary purpose
      tech_note_link: nan
      time_period: '2019'
      update_cadence: Periodically
    share_level: everyone
    snippet: null
    tags: Trucks;
    title: Safety_Rest_Area
