dataset:
  layer_params:
    accessInformation: 
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 
      contact_city: Seattle
      contact_email: cpeak@psrc.org
      contact_name: Chris Peak
      contact_phone: 206-464-7536 
      contact_state: Washington
      contact_street_address: 1201 3rd Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 
      data_source: 
      date_last_updated: 
      summary: 
      fields:
      organization_name: PSRC
      psrc_website: https://www.psrc.org
      summary_footer: 
      supplemental_info: ''
      summary_addendum: 
      time_period: 
      update_cadence: 
    share_level: everyone
    snippet: null
    groups: hub- GIS;PSRC Data Portal Content;hub- Transportation
    spatial_data: True
    tags: Employment;
    title: Transit_Routes_2018_RTP
  source:
    is_simple: true
    feature_dataset: 'rtp_2022'
    has_donut_holes: true
    schema_name: dbo
    sql_query: null
    table_name: transit_routes_2018_rtp

