dataset:
  layer_params:
    accessInformation: 
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: 
      contact_city: Seattle
      contact_email: cpeak@psrc.org
      contact_name: Chris Peak
      contact_phone: 206-464-7536 
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: 
      data_source: 
      date_last_updated: 
      description: 
      fields:
      organization_name: PSRC
      psrc_website: https://www.psrc.org
      summary_purpose: 
      supplemental_info: ''
      tech_note_link: 
      time_period: 
      update_cadence: 
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Employment;
    title: Transit_Stops_2018_RTP
  source:
    is_simple: true
    feature_dataset: ''
    has_donut_holes: false
    schema_name: dbo
    sql_query: null
    table_name: transit_stops_2018_rtp

