dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: ''
      constraints: This layer represents tribal reservation boundaries and off-reservation
        trust lands in King, Snohomish, Pierce, and Kitsap counties. The boundaries
        are recognized by the U.S. Bureau of Indian Affairs.
      contact_city: Seattle
      contact_email: DHanson@psrc.org
      contact_name: Drew Hanson
      contact_phone: 206-971-3269
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: Data displays both reservation land and tribally owned properties.
      data_source: Washington State Department of Transportation
      date_last_updated: 02/2018
      description: This layer represents tribal land boundaries in King, Snohomish,
        Pierce, and Kitsap counties. The boundaries are recognized by the U.S. Bureau
        of Indian Affairs.
      fields:
      - description: (no description)
        title: FID
      - description: Tribe name (short version)
        title: tribe_shor
      - description: Tribe name (full version)
        title: tribe_full
      - description: Land description
        title: tribal_lan
      - description: Land type
        title: triballa_1
      - description: (no description)
        title: lastupdate
      - description: (no description)
        title: globalid
      - description: (no description)
        title: shape_star
      - description: (no description)
        title: shape_stle
      - description: Acreage
        title: acres
      psrc_website: ''
      summary_purpose: 
      supplemental_info: 'Data was originally obtained from the Washington Department
        of Transportation. '
      tech_note_link: ''
      time_period: '2021'
      update_cadence: As needed
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Geographic Boundaries;Tribes;
    title: tribal_lands
  source:
    feature_dataset: ''
    has_donut_holes: false
    is_simple: true
    schema_name: dbo
    sql_query: null
    table_name: tribal_land
