dataset:
  layer_params:
    accessInformation: null
    allow_edits: false
    licenseInfo: null
    metadata:
      assessment: ''
      contact_city: Seattle
      contact_email: gsimonson@psrc.org
      contact_name: Gary Simonson
      contact_phone: 206-971-3276
      contact_state: Washington
      contact_street_address: 1011 Western Ave. Ste. 500
      contact_zip: 98101
      data_lineage: WSDOT surveys all weigh stations across the state
      data_source: Washington State Department of Transportation
      date_last_updated: 01/2020
      description: The weigh stations dataset contains all of the truck weigh stations
        locations, as well as information about parking and amenities at the facilities.
      fields:
      - description: (no description)
        title: OBJECTID
      - description: (no description)
        title: name
      - description: Scale ID Number
        title: scale_hous
      - description: (no description)
        title: corridor
      - description: (no description)
        title: lat
      - description: (no description)
        title: long_
      - description: (no description)
        title: mile_post
      - description: (no description)
        title: mp_display
      - description: (no description)
        title: city
      - description: (no description)
        title: county
      - description: (no description)
        title: srid
      - description: (no description)
        title: srmp
      - description: (no description)
        title: parking_st
      - description: Does it have restrooms?
        title: amenities
      - description: (no description)
        title: latlong
      organization_name: Puget Sound Regional Council
      psrc_website: ''
      summary_purpose: ''
      supplemental_info: ''
      tech_note_link: ''
      time_period: '2020'
      update_cadence: Every few years
    share_level: everyone
    snippet: null
    spatial_data: true
    tags: Trucks;Parking;Freight;
    title: Weigh_Stations
  source:
    is_simple: false
    feature_dataset: transportation_freight
    has_donut_holes: false
    schema_name: dbo
    sql_query: select Shape.STAsText() as Shape_wkt, OBJECTID, [name],
      scale_house, corridor, lat, long_, mile_post, mp_display, city,
      county, srid, srmp, parking_stall, amenities
      from dbo.WEIGH_STATION
    table_name: Weigh_Station